/* Generated by Yosys 0.51 (git sha1 c4b519022, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

/* top =  1  */
/* src = "../rtl/timer_unit/timer_unit.sv:37.8" */
module timer_unit(clk_i, rst_ni, ref_clk_i, req_i, addr_i, wen_i, wdata_i, be_i, id_i, gnt_o, r_valid_o, r_opc_o, r_id_o, r_rdata_o, event_lo_i, event_hi_i, irq_lo_o, irq_hi_o, busy_o);
  wire \$auto$builder.cc:338:Biop$100 ;
  wire \$auto$builder.cc:338:Biop$104 ;
  wire \$auto$builder.cc:338:Biop$108 ;
  wire \$auto$builder.cc:338:Biop$112 ;
  wire \$auto$builder.cc:338:Biop$120 ;
  wire \$auto$builder.cc:338:Biop$124 ;
  wire \$auto$builder.cc:338:Biop$147 ;
  wire \$auto$builder.cc:338:Biop$158 ;
  wire \$auto$builder.cc:338:Biop$170 ;
  wire \$auto$builder.cc:338:Biop$183 ;
  wire \$auto$builder.cc:338:Biop$195 ;
  wire \$auto$builder.cc:338:Biop$207 ;
  wire \$auto$builder.cc:338:Biop$230 ;
  wire \$auto$builder.cc:338:Biop$237 ;
  wire \$auto$builder.cc:338:Biop$247 ;
  wire \$auto$builder.cc:338:Biop$249 ;
  wire \$auto$builder.cc:338:Biop$251 ;
  wire \$auto$builder.cc:338:Biop$259 ;
  wire \$auto$builder.cc:338:Biop$267 ;
  wire \$auto$builder.cc:338:Biop$28 ;
  wire \$auto$builder.cc:338:Biop$283 ;
  wire \$auto$builder.cc:338:Biop$285 ;
  wire \$auto$builder.cc:338:Biop$287 ;
  wire \$auto$builder.cc:338:Biop$295 ;
  wire \$auto$builder.cc:338:Biop$303 ;
  wire \$auto$builder.cc:338:Biop$319 ;
  wire \$auto$builder.cc:338:Biop$331 ;
  wire \$auto$builder.cc:338:Biop$353 ;
  wire \$auto$builder.cc:338:Biop$382 ;
  wire \$auto$builder.cc:338:Biop$384 ;
  wire \$auto$builder.cc:338:Biop$397 ;
  wire \$auto$builder.cc:338:Biop$407 ;
  wire \$auto$builder.cc:338:Biop$56 ;
  wire \$auto$builder.cc:338:Biop$60 ;
  wire \$auto$builder.cc:338:Biop$96 ;
  wire \$auto$builder.cc:364:Unop$26 ;
  wire \$auto$opt_dff.cc:194:make_patterns_logic$1198 ;
  wire \$auto$opt_dff.cc:194:make_patterns_logic$1200 ;
  wire \$auto$opt_dff.cc:194:make_patterns_logic$1209 ;
  wire \$auto$opt_dff.cc:194:make_patterns_logic$1211 ;
  wire \$auto$opt_dff.cc:219:make_patterns_logic$1189 ;
  wire \$auto$opt_dff.cc:219:make_patterns_logic$1192 ;
  wire \$auto$opt_dff.cc:219:make_patterns_logic$1195 ;
  wire \$auto$opt_dff.cc:219:make_patterns_logic$1202 ;
  wire \$auto$opt_dff.cc:219:make_patterns_logic$1206 ;
  wire \$auto$opt_dff.cc:219:make_patterns_logic$1213 ;
  wire \$auto$opt_share.cc:222:merge_operators$1217 ;
  wire \$auto$rtlil.cc:2874:Mux$1184 ;
  wire \$auto$rtlil.cc:2874:Mux$1187 ;
  wire \$auto$rtlil.cc:2874:Mux$1219 ;
  /* src = "../rtl/timer_unit/timer_unit.sv:285.14-305.21" */
  wire [31:0] \$auto$slang_frontend.cc:694:finish$\r_rdata_o$150 ;
  /* src = "../rtl/timer_unit/timer_unit.sv:183.14-215.21" */
  wire [31:0] \$auto$slang_frontend.cc:694:finish$\s_cfg_hi$38 ;
  /* src = "../rtl/timer_unit/timer_unit.sv:180.9-216.14" */
  /* unused_bits = "2 4 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" */
  wire [31:0] \$auto$slang_frontend.cc:694:finish$\s_cfg_hi$48 ;
  /* src = "../rtl/timer_unit/timer_unit.sv:243.7-244.37" */
  wire \$auto$slang_frontend.cc:694:finish$\s_cfg_hi[0]$127 ;
  /* src = "../rtl/timer_unit/timer_unit.sv:240.7-245.9" */
  wire \$auto$slang_frontend.cc:694:finish$\s_cfg_hi[0]$128 ;
  /* src = "../rtl/timer_unit/timer_unit.sv:183.14-215.21" */
  wire [31:0] \$auto$slang_frontend.cc:694:finish$\s_cfg_lo$37 ;
  /* src = "../rtl/timer_unit/timer_unit.sv:180.9-216.14" */
  /* unused_bits = "2 4 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" */
  wire [31:0] \$auto$slang_frontend.cc:694:finish$\s_cfg_lo$47 ;
  /* src = "../rtl/timer_unit/timer_unit.sv:225.5-226.33" */
  wire \$auto$slang_frontend.cc:694:finish$\s_cfg_lo[0]$75 ;
  /* src = "../rtl/timer_unit/timer_unit.sv:230.6-231.33" */
  wire \$auto$slang_frontend.cc:694:finish$\s_cfg_lo[0]$88 ;
  /* src = "../rtl/timer_unit/timer_unit.sv:223.7-232.12" */
  wire \$auto$slang_frontend.cc:694:finish$\s_cfg_lo[0]$89 ;
  /* src = "../rtl/timer_unit/timer_unit.sv:422.9-436.9" */
  wire \$auto$slang_frontend.cc:694:finish$\s_enable_count_hi$308 ;
  /* src = "../rtl/timer_unit/timer_unit.sv:417.7-436.9" */
  wire \$auto$slang_frontend.cc:694:finish$\s_enable_count_hi$310 ;
  /* src = "../rtl/timer_unit/timer_unit.sv:415.2-437.7" */
  wire \$auto$slang_frontend.cc:694:finish$\s_enable_count_hi$312 ;
  /* src = "../rtl/timer_unit/timer_unit.sv:442.6-463.6" */
  wire \$auto$slang_frontend.cc:694:finish$\s_enable_count_hi$369 ;
  /* src = "../rtl/timer_unit/timer_unit.sv:397.9-411.9" */
  wire \$auto$slang_frontend.cc:694:finish$\s_enable_count_lo$272 ;
  /* src = "../rtl/timer_unit/timer_unit.sv:392.7-411.9" */
  wire \$auto$slang_frontend.cc:694:finish$\s_enable_count_lo$274 ;
  /* src = "../rtl/timer_unit/timer_unit.sv:390.2-412.7" */
  wire \$auto$slang_frontend.cc:694:finish$\s_enable_count_lo$276 ;
  /* src = "../rtl/timer_unit/timer_unit.sv:427.4-436.9" */
  wire \$auto$slang_frontend.cc:694:finish$\s_enable_count_prescaler_hi$307 ;
  /* src = "../rtl/timer_unit/timer_unit.sv:422.9-436.9" */
  wire \$auto$slang_frontend.cc:694:finish$\s_enable_count_prescaler_hi$309 ;
  /* src = "../rtl/timer_unit/timer_unit.sv:417.7-436.9" */
  wire \$auto$slang_frontend.cc:694:finish$\s_enable_count_prescaler_hi$311 ;
  /* src = "../rtl/timer_unit/timer_unit.sv:402.4-411.9" */
  wire \$auto$slang_frontend.cc:694:finish$\s_enable_count_prescaler_lo$271 ;
  /* src = "../rtl/timer_unit/timer_unit.sv:397.9-411.9" */
  wire \$auto$slang_frontend.cc:694:finish$\s_enable_count_prescaler_lo$273 ;
  /* src = "../rtl/timer_unit/timer_unit.sv:392.7-411.9" */
  wire \$auto$slang_frontend.cc:694:finish$\s_enable_count_prescaler_lo$275 ;
  /* src = "../rtl/timer_unit/timer_unit.sv:390.2-412.7" */
  wire \$auto$slang_frontend.cc:694:finish$\s_enable_count_prescaler_lo$277 ;
  /* src = "../rtl/timer_unit/timer_unit.sv:447.11-463.6" */
  wire \$auto$slang_frontend.cc:694:finish$\s_enable_count_prescaler_lo$367 ;
  /* src = "../rtl/timer_unit/timer_unit.sv:442.6-463.6" */
  wire \$auto$slang_frontend.cc:694:finish$\s_enable_count_prescaler_lo$370 ;
  /* src = "../rtl/timer_unit/timer_unit.sv:353.7-366.12" */
  wire \$auto$slang_frontend.cc:694:finish$\s_reset_count_hi$224 ;
  /* src = "../rtl/timer_unit/timer_unit.sv:330.7-343.12" */
  wire \$auto$slang_frontend.cc:694:finish$\s_reset_count_lo$187 ;
  /* src = "../rtl/timer_unit/timer_unit.sv:183.14-215.21" */
  wire \$auto$slang_frontend.cc:694:finish$\s_reset_timer_hi$36 ;
  /* src = "../rtl/timer_unit/timer_unit.sv:183.14-215.21" */
  wire \$auto$slang_frontend.cc:694:finish$\s_reset_timer_lo$35 ;
  /* src = "../rtl/timer_unit/timer_unit.sv:183.14-215.21" */
  wire \$auto$slang_frontend.cc:694:finish$\s_start_timer_hi$34 ;
  /* src = "../rtl/timer_unit/timer_unit.sv:183.14-215.21" */
  wire \$auto$slang_frontend.cc:694:finish$\s_start_timer_lo$33 ;
  /* src = "../rtl/timer_unit/timer_unit.sv:183.14-215.21" */
  wire \$auto$slang_frontend.cc:694:finish$\s_write_counter_hi$32 ;
  /* src = "../rtl/timer_unit/timer_unit.sv:183.14-215.21" */
  wire \$auto$slang_frontend.cc:694:finish$\s_write_counter_lo$31 ;
  wire \$procmux$645_CMP ;
  wire \$procmux$646_CMP ;
  wire \$procmux$647_CMP ;
  wire \$procmux$648_CMP ;
  wire \$procmux$649_CMP ;
  wire \$procmux$650_CMP ;
  wire \$procmux$735_CMP ;
  wire \$procmux$744_CMP ;
  wire \$procmux$756_CMP ;
  wire \$procmux$769_CMP ;
  /* src = "../rtl/timer_unit/timer_unit.sv:91.56" */
  wire [1:0] CS;
  wire NS;
  /* src = "../rtl/timer_unit/timer_unit.sv:48.39" */
  input [31:0] addr_i;
  wire [31:0] addr_i;
  /* src = "../rtl/timer_unit/timer_unit.sv:51.39" */
  input [3:0] be_i;
  wire [3:0] be_i;
  /* src = "../rtl/timer_unit/timer_unit.sv:66.39" */
  output busy_o;
  wire busy_o;
  /* src = "../rtl/timer_unit/timer_unit.sv:42.39" */
  input clk_i;
  wire clk_i;
  /* src = "../rtl/timer_unit/timer_unit.sv:61.39" */
  input event_hi_i;
  wire event_hi_i;
  /* src = "../rtl/timer_unit/timer_unit.sv:60.39" */
  input event_lo_i;
  wire event_lo_i;
  /* src = "../rtl/timer_unit/timer_unit.sv:53.39" */
  output gnt_o;
  wire gnt_o;
  /* src = "../rtl/timer_unit/timer_unit.sv:52.39" */
  input [4:0] id_i;
  wire [4:0] id_i;
  /* src = "../rtl/timer_unit/timer_unit.sv:64.39" */
  output irq_hi_o;
  wire irq_hi_o;
  /* src = "../rtl/timer_unit/timer_unit.sv:63.39" */
  output irq_lo_o;
  wire irq_lo_o;
  /* src = "../rtl/timer_unit/timer_unit.sv:57.39" */
  output [4:0] r_id_o;
  wire [4:0] r_id_o;
  /* src = "../rtl/timer_unit/timer_unit.sv:56.39" */
  output r_opc_o;
  wire r_opc_o;
  /* src = "../rtl/timer_unit/timer_unit.sv:58.39" */
  output [31:0] r_rdata_o;
  wire [31:0] r_rdata_o;
  /* src = "../rtl/timer_unit/timer_unit.sv:55.39" */
  output r_valid_o;
  wire r_valid_o;
  /* src = "../rtl/timer_unit/timer_unit.sv:45.39" */
  input ref_clk_i;
  wire ref_clk_i;
  /* src = "../rtl/timer_unit/timer_unit.sv:47.39" */
  input req_i;
  wire req_i;
  /* src = "../rtl/timer_unit/timer_unit.sv:43.39" */
  input rst_ni;
  wire rst_ni;
  /* src = "../rtl/timer_unit/timer_unit.sv:70.25" */
  /* unused_bits = "6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" */
  wire [31:0] s_addr;
  /* src = "../rtl/timer_unit/timer_unit.sv:80.25" */
  /* unused_bits = "2 4 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" */
  wire [31:0] s_cfg_hi;
  /* src = "../rtl/timer_unit/timer_unit.sv:80.35" */
  wire [31:0] s_cfg_hi_reg;
  /* src = "../rtl/timer_unit/timer_unit.sv:79.25" */
  /* unused_bits = "2 4 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" */
  wire [31:0] s_cfg_lo;
  /* src = "../rtl/timer_unit/timer_unit.sv:79.35" */
  wire [31:0] s_cfg_lo_reg;
  /* src = "../rtl/timer_unit/timer_unit.sv:86.37" */
  wire s_enable_count_hi;
  /* src = "../rtl/timer_unit/timer_unit.sv:86.19" */
  wire s_enable_count_lo;
  /* src = "../rtl/timer_unit/timer_unit.sv:86.83" */
  wire s_enable_count_prescaler_hi;
  /* src = "../rtl/timer_unit/timer_unit.sv:86.55" */
  wire s_enable_count_prescaler_lo;
  /* src = "../rtl/timer_unit/timer_unit.sv:75.19" */
  wire s_ref_clk0;
  /* src = "../rtl/timer_unit/timer_unit.sv:75.31" */
  wire s_ref_clk1;
  /* src = "../rtl/timer_unit/timer_unit.sv:75.43" */
  wire s_ref_clk2;
  /* src = "../rtl/timer_unit/timer_unit.sv:75.55" */
  wire s_ref_clk3;
  /* src = "../rtl/timer_unit/timer_unit.sv:75.67" */
  wire s_ref_clk_edge;
  /* src = "../rtl/timer_unit/timer_unit.sv:75.83" */
  wire s_ref_clk_edge_del;
  /* src = "../rtl/timer_unit/timer_unit.sv:69.19" */
  wire s_req;
  /* src = "../rtl/timer_unit/timer_unit.sv:87.36" */
  wire s_reset_count_hi;
  /* src = "../rtl/timer_unit/timer_unit.sv:87.19" */
  wire s_reset_count_lo;
  /* src = "../rtl/timer_unit/timer_unit.sv:87.80" */
  wire s_reset_count_prescaler_hi;
  /* src = "../rtl/timer_unit/timer_unit.sv:87.53" */
  wire s_reset_count_prescaler_lo;
  /* src = "../rtl/timer_unit/timer_unit.sv:73.70" */
  wire s_reset_timer_hi;
  /* src = "../rtl/timer_unit/timer_unit.sv:73.53" */
  wire s_reset_timer_lo;
  /* src = "../rtl/timer_unit/timer_unit.sv:73.36" */
  wire s_start_timer_hi;
  /* src = "../rtl/timer_unit/timer_unit.sv:73.19" */
  wire s_start_timer_lo;
  /* src = "../rtl/timer_unit/timer_unit.sv:88.39" */
  wire s_target_reached_hi;
  /* src = "../rtl/timer_unit/timer_unit.sv:88.19" */
  wire s_target_reached_lo;
  /* src = "../rtl/timer_unit/timer_unit.sv:88.90" */
  wire s_target_reached_prescaler_hi;
  /* src = "../rtl/timer_unit/timer_unit.sv:88.59" */
  wire s_target_reached_prescaler_lo;
  /* src = "../rtl/timer_unit/timer_unit.sv:84.41" */
  wire [31:0] s_timer_cmp_hi_reg;
  /* src = "../rtl/timer_unit/timer_unit.sv:83.41" */
  wire [31:0] s_timer_cmp_lo_reg;
  /* src = "../rtl/timer_unit/timer_unit.sv:82.25" */
  wire [31:0] s_timer_val_hi;
  /* src = "../rtl/timer_unit/timer_unit.sv:81.25" */
  wire [31:0] s_timer_val_lo;
  /* src = "../rtl/timer_unit/timer_unit.sv:69.25" */
  wire s_wen;
  /* src = "../rtl/timer_unit/timer_unit.sv:72.39" */
  wire s_write_counter_hi;
  /* src = "../rtl/timer_unit/timer_unit.sv:72.19" */
  wire s_write_counter_lo;
  /* src = "../rtl/timer_unit/timer_unit.sv:50.39" */
  input [31:0] wdata_i;
  wire [31:0] wdata_i;
  /* src = "../rtl/timer_unit/timer_unit.sv:49.39" */
  input wen_i;
  wire wen_i;
  \$not  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) \$auto$builder.cc:330:Biop$103  (
    .A(s_cfg_hi_reg[31]),
    .Y(\$auto$builder.cc:338:Biop$104 )
  );
  \$logic_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) \$auto$builder.cc:330:Biop$107  (
    .A(\$auto$builder.cc:338:Biop$104 ),
    .B(s_cfg_hi[5]),
    .Y(\$auto$builder.cc:338:Biop$108 )
  );
  \$logic_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) \$auto$builder.cc:330:Biop$111  (
    .A(\$auto$builder.cc:338:Biop$108 ),
    .B(s_target_reached_hi),
    .Y(\$auto$builder.cc:338:Biop$112 )
  );
  \$logic_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) \$auto$builder.cc:330:Biop$119  (
    .A(s_cfg_lo[5]),
    .B(s_target_reached_lo),
    .Y(\$auto$builder.cc:338:Biop$120 )
  );
  \$logic_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) \$auto$builder.cc:330:Biop$123  (
    .A(\$auto$builder.cc:338:Biop$120 ),
    .B(s_target_reached_hi),
    .Y(\$auto$builder.cc:338:Biop$124 )
  );
  \$logic_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) \$auto$builder.cc:330:Biop$146  (
    .A(CS[0]),
    .B(s_wen),
    .Y(\$auto$builder.cc:338:Biop$147 )
  );
  \$or  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) \$auto$builder.cc:330:Biop$157  (
    .A(s_cfg_lo_reg[1]),
    .B(s_reset_timer_lo),
    .Y(\$auto$builder.cc:338:Biop$158 )
  );
  \$logic_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) \$auto$builder.cc:330:Biop$169  (
    .A(s_cfg_lo_reg[4]),
    .B(s_target_reached_lo),
    .Y(\$auto$builder.cc:338:Biop$170 )
  );
  \$logic_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) \$auto$builder.cc:330:Biop$182  (
    .A(\$auto$builder.cc:338:Biop$170 ),
    .B(s_target_reached_hi),
    .Y(\$auto$builder.cc:338:Biop$183 )
  );
  \$or  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) \$auto$builder.cc:330:Biop$194  (
    .A(s_cfg_hi_reg[1]),
    .B(s_reset_timer_hi),
    .Y(\$auto$builder.cc:338:Biop$195 )
  );
  \$logic_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) \$auto$builder.cc:330:Biop$206  (
    .A(s_cfg_hi_reg[4]),
    .B(s_target_reached_hi),
    .Y(\$auto$builder.cc:338:Biop$207 )
  );
  \$logic_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) \$auto$builder.cc:330:Biop$229  (
    .A(s_cfg_lo_reg[6]),
    .B(s_target_reached_prescaler_lo),
    .Y(\$auto$builder.cc:338:Biop$230 )
  );
  \$logic_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) \$auto$builder.cc:330:Biop$236  (
    .A(s_cfg_hi_reg[6]),
    .B(s_target_reached_prescaler_hi),
    .Y(\$auto$builder.cc:338:Biop$237 )
  );
  \$not  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) \$auto$builder.cc:330:Biop$246  (
    .A(s_cfg_lo_reg[6]),
    .Y(\$auto$builder.cc:338:Biop$247 )
  );
  \$not  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) \$auto$builder.cc:330:Biop$248  (
    .A(s_cfg_lo_reg[7]),
    .Y(\$auto$builder.cc:338:Biop$249 )
  );
  \$logic_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) \$auto$builder.cc:330:Biop$250  (
    .A(\$auto$builder.cc:338:Biop$247 ),
    .B(\$auto$builder.cc:338:Biop$249 ),
    .Y(\$auto$builder.cc:338:Biop$251 )
  );
  \$logic_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) \$auto$builder.cc:330:Biop$258  (
    .A(\$auto$builder.cc:338:Biop$247 ),
    .B(s_cfg_lo_reg[7]),
    .Y(\$auto$builder.cc:338:Biop$259 )
  );
  \$logic_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) \$auto$builder.cc:330:Biop$266  (
    .A(s_cfg_lo_reg[6]),
    .B(s_cfg_lo_reg[7]),
    .Y(\$auto$builder.cc:338:Biop$267 )
  );
  \$logic_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) \$auto$builder.cc:330:Biop$27  (
    .A(req_i),
    .B(\$auto$builder.cc:364:Unop$26 ),
    .Y(\$auto$builder.cc:338:Biop$28 )
  );
  \$not  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) \$auto$builder.cc:330:Biop$282  (
    .A(s_cfg_hi_reg[6]),
    .Y(\$auto$builder.cc:338:Biop$283 )
  );
  \$not  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) \$auto$builder.cc:330:Biop$284  (
    .A(s_cfg_hi_reg[7]),
    .Y(\$auto$builder.cc:338:Biop$285 )
  );
  \$logic_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) \$auto$builder.cc:330:Biop$286  (
    .A(\$auto$builder.cc:338:Biop$283 ),
    .B(\$auto$builder.cc:338:Biop$285 ),
    .Y(\$auto$builder.cc:338:Biop$287 )
  );
  \$logic_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) \$auto$builder.cc:330:Biop$294  (
    .A(\$auto$builder.cc:338:Biop$283 ),
    .B(s_cfg_hi_reg[7]),
    .Y(\$auto$builder.cc:338:Biop$295 )
  );
  \$logic_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) \$auto$builder.cc:330:Biop$302  (
    .A(s_cfg_hi_reg[6]),
    .B(s_cfg_hi_reg[7]),
    .Y(\$auto$builder.cc:338:Biop$303 )
  );
  \$logic_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) \$auto$builder.cc:330:Biop$318  (
    .A(s_cfg_lo_reg[0]),
    .B(s_cfg_lo_reg[31]),
    .Y(\$auto$builder.cc:338:Biop$319 )
  );
  \$eq  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd32),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd32),
    .Y_WIDTH(32'd1)
  ) \$auto$builder.cc:330:Biop$330  (
    .A(s_timer_val_lo),
    .B(32'd4294967295),
    .Y(\$auto$builder.cc:338:Biop$331 )
  );
  \$logic_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) \$auto$builder.cc:330:Biop$342  (
    .A(\$auto$rtlil.cc:2874:Mux$1219 ),
    .B(\$auto$builder.cc:338:Biop$331 ),
    .Y(\$auto$opt_share.cc:222:merge_operators$1217 )
  );
  \$logic_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) \$auto$builder.cc:330:Biop$352  (
    .A(s_target_reached_prescaler_lo),
    .B(s_ref_clk_edge_del),
    .Y(\$auto$builder.cc:338:Biop$353 )
  );
  \$and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) \$auto$builder.cc:330:Biop$381  (
    .A(s_target_reached_hi),
    .B(s_cfg_hi_reg[2]),
    .Y(\$auto$builder.cc:338:Biop$382 )
  );
  \$and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) \$auto$builder.cc:330:Biop$383  (
    .A(s_target_reached_lo),
    .B(s_target_reached_hi),
    .Y(\$auto$builder.cc:338:Biop$384 )
  );
  \$and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) \$auto$builder.cc:330:Biop$385  (
    .A(\$auto$rtlil.cc:2874:Mux$1184 ),
    .B(s_cfg_lo_reg[2]),
    .Y(irq_lo_o)
  );
  \$not  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) \$auto$builder.cc:330:Biop$396  (
    .A(s_ref_clk2),
    .Y(\$auto$builder.cc:338:Biop$397 )
  );
  \$and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) \$auto$builder.cc:330:Biop$398  (
    .A(s_ref_clk1),
    .B(\$auto$builder.cc:338:Biop$397 ),
    .Y(s_ref_clk_edge)
  );
  \$not  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) \$auto$builder.cc:330:Biop$406  (
    .A(s_ref_clk3),
    .Y(\$auto$builder.cc:338:Biop$407 )
  );
  \$and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) \$auto$builder.cc:330:Biop$408  (
    .A(s_ref_clk2),
    .B(\$auto$builder.cc:338:Biop$407 ),
    .Y(s_ref_clk_edge_del)
  );
  \$or  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) \$auto$builder.cc:330:Biop$414  (
    .A(s_cfg_hi_reg[0]),
    .B(s_cfg_lo_reg[0]),
    .Y(busy_o)
  );
  \$logic_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) \$auto$builder.cc:330:Biop$55  (
    .A(event_lo_i),
    .B(s_cfg_lo[3]),
    .Y(\$auto$builder.cc:338:Biop$56 )
  );
  \$or  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) \$auto$builder.cc:330:Biop$59  (
    .A(\$auto$builder.cc:338:Biop$56 ),
    .B(s_start_timer_lo),
    .Y(\$auto$builder.cc:338:Biop$60 )
  );
  \$logic_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) \$auto$builder.cc:330:Biop$95  (
    .A(event_hi_i),
    .B(s_cfg_hi[3]),
    .Y(\$auto$builder.cc:338:Biop$96 )
  );
  \$or  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) \$auto$builder.cc:330:Biop$99  (
    .A(\$auto$builder.cc:338:Biop$96 ),
    .B(s_start_timer_hi),
    .Y(\$auto$builder.cc:338:Biop$100 )
  );
  \$not  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) \$auto$builder.cc:359:Unop$25  (
    .A(wen_i),
    .Y(\$auto$builder.cc:364:Unop$26 )
  );
  /* src = "../rtl/timer_unit/timer_unit.sv:259.4" */
  \$adffe  #(
    .ARST_POLARITY(32'd0),
    .ARST_VALUE(32'd0),
    .CLK_POLARITY(32'd1),
    .EN_POLARITY(32'd1),
    .WIDTH(32'd32)
  ) \$auto$ff.cc:266:slice$1188  (
    .ARST(rst_ni),
    .CLK(clk_i),
    .D(wdata_i),
    .EN(\$auto$opt_dff.cc:219:make_patterns_logic$1189 ),
    .Q(s_timer_cmp_lo_reg)
  );
  /* src = "../rtl/timer_unit/timer_unit.sv:259.4" */
  \$adffe  #(
    .ARST_POLARITY(32'd0),
    .ARST_VALUE(32'd0),
    .CLK_POLARITY(32'd1),
    .EN_POLARITY(32'd1),
    .WIDTH(32'd32)
  ) \$auto$ff.cc:266:slice$1191  (
    .ARST(rst_ni),
    .CLK(clk_i),
    .D(wdata_i),
    .EN(\$auto$opt_dff.cc:219:make_patterns_logic$1192 ),
    .Q(s_timer_cmp_hi_reg)
  );
  /* src = "../rtl/timer_unit/timer_unit.sv:259.4" */
  \$adffe  #(
    .ARST_POLARITY(32'd0),
    .ARST_VALUE(28'h0000000),
    .CLK_POLARITY(32'd1),
    .EN_POLARITY(32'd1),
    .WIDTH(32'd28)
  ) \$auto$ff.cc:266:slice$1194  (
    .ARST(rst_ni),
    .CLK(clk_i),
    .D({ wdata_i[31:6], wdata_i[4], wdata_i[2] }),
    .EN(\$auto$opt_dff.cc:219:make_patterns_logic$1195 ),
    .Q({ s_cfg_lo_reg[31:6], s_cfg_lo_reg[4], s_cfg_lo_reg[2] })
  );
  /* src = "../rtl/timer_unit/timer_unit.sv:259.4" */
  \$adffe  #(
    .ARST_POLARITY(32'd0),
    .ARST_VALUE(1'h0),
    .CLK_POLARITY(32'd1),
    .EN_POLARITY(32'd1),
    .WIDTH(32'd1)
  ) \$auto$ff.cc:266:slice$1197  (
    .ARST(rst_ni),
    .CLK(clk_i),
    .D(s_cfg_lo[1]),
    .EN(\$auto$opt_dff.cc:219:make_patterns_logic$1202 ),
    .Q(s_cfg_lo_reg[1])
  );
  /* src = "../rtl/timer_unit/timer_unit.sv:259.4" */
  \$adff  #(
    .ARST_POLARITY(32'd0),
    .ARST_VALUE(3'h0),
    .CLK_POLARITY(32'd1),
    .WIDTH(32'd3)
  ) \$auto$ff.cc:266:slice$1204  (
    .ARST(rst_ni),
    .CLK(clk_i),
    .D({ s_cfg_lo[5], s_cfg_lo[3], s_cfg_lo[0] }),
    .Q({ s_cfg_lo_reg[5], s_cfg_lo_reg[3], s_cfg_lo_reg[0] })
  );
  /* src = "../rtl/timer_unit/timer_unit.sv:259.4" */
  \$adffe  #(
    .ARST_POLARITY(32'd0),
    .ARST_VALUE(28'h0000000),
    .CLK_POLARITY(32'd1),
    .EN_POLARITY(32'd1),
    .WIDTH(32'd28)
  ) \$auto$ff.cc:266:slice$1205  (
    .ARST(rst_ni),
    .CLK(clk_i),
    .D({ wdata_i[31:6], wdata_i[4], wdata_i[2] }),
    .EN(\$auto$opt_dff.cc:219:make_patterns_logic$1206 ),
    .Q({ s_cfg_hi_reg[31:6], s_cfg_hi_reg[4], s_cfg_hi_reg[2] })
  );
  /* src = "../rtl/timer_unit/timer_unit.sv:259.4" */
  \$adffe  #(
    .ARST_POLARITY(32'd0),
    .ARST_VALUE(1'h0),
    .CLK_POLARITY(32'd1),
    .EN_POLARITY(32'd1),
    .WIDTH(32'd1)
  ) \$auto$ff.cc:266:slice$1208  (
    .ARST(rst_ni),
    .CLK(clk_i),
    .D(s_cfg_hi[1]),
    .EN(\$auto$opt_dff.cc:219:make_patterns_logic$1213 ),
    .Q(s_cfg_hi_reg[1])
  );
  /* src = "../rtl/timer_unit/timer_unit.sv:259.4" */
  \$adff  #(
    .ARST_POLARITY(32'd0),
    .ARST_VALUE(3'h0),
    .CLK_POLARITY(32'd1),
    .WIDTH(32'd3)
  ) \$auto$ff.cc:266:slice$1215  (
    .ARST(rst_ni),
    .CLK(clk_i),
    .D({ s_cfg_hi[5], s_cfg_hi[3], s_cfg_hi[0] }),
    .Q({ s_cfg_hi_reg[5], s_cfg_hi_reg[3], s_cfg_hi_reg[0] })
  );
  /* src = "../rtl/timer_unit/timer_unit.sv:98.4" */
  \$adff  #(
    .ARST_POLARITY(32'd0),
    .ARST_VALUE(1'h0),
    .CLK_POLARITY(32'd1),
    .WIDTH(32'd1)
  ) \$auto$ff.cc:266:slice$1216  (
    .ARST(rst_ni),
    .CLK(clk_i),
    .D(req_i),
    .Q(CS[0])
  );
  \$reduce_bool  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd2),
    .Y_WIDTH(32'd1)
  ) \$auto$opt_dff.cc:195:make_patterns_logic$1199  (
    .A({ \$auto$builder.cc:338:Biop$28 , s_reset_count_lo }),
    .Y(\$auto$opt_dff.cc:194:make_patterns_logic$1198 )
  );
  \$ne  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd3),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd3),
    .Y_WIDTH(32'd1)
  ) \$auto$opt_dff.cc:195:make_patterns_logic$1201  (
    .A({ \$procmux$769_CMP , \$auto$builder.cc:338:Biop$28 , s_reset_count_lo }),
    .B(3'h2),
    .Y(\$auto$opt_dff.cc:194:make_patterns_logic$1200 )
  );
  \$reduce_bool  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd2),
    .Y_WIDTH(32'd1)
  ) \$auto$opt_dff.cc:195:make_patterns_logic$1210  (
    .A({ \$auto$builder.cc:338:Biop$28 , s_reset_count_hi }),
    .Y(\$auto$opt_dff.cc:194:make_patterns_logic$1209 )
  );
  \$ne  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd3),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd3),
    .Y_WIDTH(32'd1)
  ) \$auto$opt_dff.cc:195:make_patterns_logic$1212  (
    .A({ \$procmux$756_CMP , \$auto$builder.cc:338:Biop$28 , s_reset_count_hi }),
    .B(3'h2),
    .Y(\$auto$opt_dff.cc:194:make_patterns_logic$1211 )
  );
  \$reduce_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd2),
    .Y_WIDTH(32'd1)
  ) \$auto$opt_dff.cc:220:make_patterns_logic$1190  (
    .A({ \$procmux$744_CMP , \$auto$builder.cc:338:Biop$28  }),
    .Y(\$auto$opt_dff.cc:219:make_patterns_logic$1189 )
  );
  \$reduce_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd2),
    .Y_WIDTH(32'd1)
  ) \$auto$opt_dff.cc:220:make_patterns_logic$1193  (
    .A({ \$procmux$735_CMP , \$auto$builder.cc:338:Biop$28  }),
    .Y(\$auto$opt_dff.cc:219:make_patterns_logic$1192 )
  );
  \$reduce_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd2),
    .Y_WIDTH(32'd1)
  ) \$auto$opt_dff.cc:220:make_patterns_logic$1196  (
    .A({ \$procmux$769_CMP , \$auto$builder.cc:338:Biop$28  }),
    .Y(\$auto$opt_dff.cc:219:make_patterns_logic$1195 )
  );
  \$reduce_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd2),
    .Y_WIDTH(32'd1)
  ) \$auto$opt_dff.cc:220:make_patterns_logic$1203  (
    .A({ \$auto$opt_dff.cc:194:make_patterns_logic$1198 , \$auto$opt_dff.cc:194:make_patterns_logic$1200  }),
    .Y(\$auto$opt_dff.cc:219:make_patterns_logic$1202 )
  );
  \$reduce_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd2),
    .Y_WIDTH(32'd1)
  ) \$auto$opt_dff.cc:220:make_patterns_logic$1207  (
    .A({ \$procmux$756_CMP , \$auto$builder.cc:338:Biop$28  }),
    .Y(\$auto$opt_dff.cc:219:make_patterns_logic$1206 )
  );
  \$reduce_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd2),
    .Y_WIDTH(32'd1)
  ) \$auto$opt_dff.cc:220:make_patterns_logic$1214  (
    .A({ \$auto$opt_dff.cc:194:make_patterns_logic$1211 , \$auto$opt_dff.cc:194:make_patterns_logic$1209  }),
    .Y(\$auto$opt_dff.cc:219:make_patterns_logic$1213 )
  );
  \$mux  #(
    .WIDTH(32'd1)
  ) \$auto$opt_share.cc:244:merge_operators$1183  (
    .A(s_target_reached_lo),
    .B(\$auto$builder.cc:338:Biop$384 ),
    .S(s_cfg_lo_reg[31]),
    .Y(\$auto$rtlil.cc:2874:Mux$1184 )
  );
  \$mux  #(
    .WIDTH(32'd1)
  ) \$auto$opt_share.cc:244:merge_operators$1186  (
    .A(s_target_reached_prescaler_lo),
    .B(\$auto$builder.cc:338:Biop$353 ),
    .S(\$auto$builder.cc:338:Biop$267 ),
    .Y(\$auto$rtlil.cc:2874:Mux$1187 )
  );
  \$mux  #(
    .WIDTH(32'd1)
  ) \$auto$opt_share.cc:244:merge_operators$1218  (
    .A(\$auto$rtlil.cc:2874:Mux$1187 ),
    .B(s_ref_clk_edge_del),
    .S(\$auto$builder.cc:338:Biop$259 ),
    .Y(\$auto$rtlil.cc:2874:Mux$1219 )
  );
  /* src = "../rtl/timer_unit/timer_unit.sv:142.4" */
  \$adff  #(
    .ARST_POLARITY(32'd0),
    .ARST_VALUE(5'h00),
    .CLK_POLARITY(32'd1),
    .WIDTH(32'd5)
  ) \$driver$r_id_o  (
    .ARST(rst_ni),
    .CLK(clk_i),
    .D(id_i),
    .Q(r_id_o)
  );
  /* src = "../rtl/timer_unit/timer_unit.sv:142.4" */
  \$adff  #(
    .ARST_POLARITY(32'd0),
    .ARST_VALUE(32'd0),
    .CLK_POLARITY(32'd1),
    .WIDTH(32'd32)
  ) \$driver$s_addr  (
    .ARST(rst_ni),
    .CLK(clk_i),
    .D(addr_i),
    .Q(s_addr)
  );
  /* src = "../rtl/timer_unit/timer_unit.sv:488.4" */
  \$adff  #(
    .ARST_POLARITY(32'd0),
    .ARST_VALUE(1'h0),
    .CLK_POLARITY(32'd1),
    .WIDTH(32'd1)
  ) \$driver$s_ref_clk0  (
    .ARST(rst_ni),
    .CLK(clk_i),
    .D(ref_clk_i),
    .Q(s_ref_clk0)
  );
  /* src = "../rtl/timer_unit/timer_unit.sv:488.4" */
  \$adff  #(
    .ARST_POLARITY(32'd0),
    .ARST_VALUE(1'h0),
    .CLK_POLARITY(32'd1),
    .WIDTH(32'd1)
  ) \$driver$s_ref_clk1  (
    .ARST(rst_ni),
    .CLK(clk_i),
    .D(s_ref_clk0),
    .Q(s_ref_clk1)
  );
  /* src = "../rtl/timer_unit/timer_unit.sv:488.4" */
  \$adff  #(
    .ARST_POLARITY(32'd0),
    .ARST_VALUE(1'h0),
    .CLK_POLARITY(32'd1),
    .WIDTH(32'd1)
  ) \$driver$s_ref_clk2  (
    .ARST(rst_ni),
    .CLK(clk_i),
    .D(s_ref_clk1),
    .Q(s_ref_clk2)
  );
  /* src = "../rtl/timer_unit/timer_unit.sv:488.4" */
  \$adff  #(
    .ARST_POLARITY(32'd0),
    .ARST_VALUE(1'h0),
    .CLK_POLARITY(32'd1),
    .WIDTH(32'd1)
  ) \$driver$s_ref_clk3  (
    .ARST(rst_ni),
    .CLK(clk_i),
    .D(s_ref_clk2),
    .Q(s_ref_clk3)
  );
  /* src = "../rtl/timer_unit/timer_unit.sv:142.4" */
  \$adff  #(
    .ARST_POLARITY(32'd0),
    .ARST_VALUE(1'h0),
    .CLK_POLARITY(32'd1),
    .WIDTH(32'd1)
  ) \$driver$s_wen  (
    .ARST(rst_ni),
    .CLK(clk_i),
    .D(wen_i),
    .Q(s_wen)
  );
  /* full_case = 32'd1 */
  /* src = "../rtl/timer_unit/timer_unit.sv:419.5-419.30|../rtl/timer_unit/timer_unit.sv:417.7-436.9" */
  \$or  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) \$procmux$1000  (
    .A(\$auto$slang_frontend.cc:694:finish$\s_enable_count_hi$308 ),
    .B(\$auto$builder.cc:338:Biop$287 ),
    .Y(\$auto$slang_frontend.cc:694:finish$\s_enable_count_hi$310 )
  );
  /* full_case = 32'd1 */
  /* src = "../rtl/timer_unit/timer_unit.sv:419.5-419.30|../rtl/timer_unit/timer_unit.sv:417.7-436.9" */
  \$mux  #(
    .WIDTH(32'd1)
  ) \$procmux$1007  (
    .A(\$auto$slang_frontend.cc:694:finish$\s_enable_count_prescaler_hi$309 ),
    .B(1'h0),
    .S(\$auto$builder.cc:338:Biop$287 ),
    .Y(\$auto$slang_frontend.cc:694:finish$\s_enable_count_prescaler_hi$311 )
  );
  /* src = "../rtl/timer_unit/timer_unit.sv:417.7-436.9|../rtl/timer_unit/timer_unit.sv:415.2-437.7" */
  \$and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) \$procmux$1013  (
    .A(s_cfg_hi_reg[0]),
    .B(\$auto$slang_frontend.cc:694:finish$\s_enable_count_prescaler_hi$311 ),
    .Y(s_enable_count_prescaler_hi)
  );
  /* src = "../rtl/timer_unit/timer_unit.sv:417.7-436.9|../rtl/timer_unit/timer_unit.sv:415.2-437.7" */
  \$and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) \$procmux$1017  (
    .A(s_cfg_hi_reg[0]),
    .B(\$auto$slang_frontend.cc:694:finish$\s_enable_count_hi$310 ),
    .Y(\$auto$slang_frontend.cc:694:finish$\s_enable_count_hi$312 )
  );
  /* full_case = 32'd1 */
  /* src = "../rtl/timer_unit/timer_unit.sv:399.7-399.42|../rtl/timer_unit/timer_unit.sv:397.9-411.9" */
  \$mux  #(
    .WIDTH(32'd1)
  ) \$procmux$1052  (
    .A(\$auto$slang_frontend.cc:694:finish$\s_enable_count_prescaler_lo$271 ),
    .B(1'h0),
    .S(\$auto$builder.cc:338:Biop$259 ),
    .Y(\$auto$slang_frontend.cc:694:finish$\s_enable_count_prescaler_lo$273 )
  );
  /* full_case = 32'd1 */
  /* src = "../rtl/timer_unit/timer_unit.sv:394.5-394.30|../rtl/timer_unit/timer_unit.sv:392.7-411.9" */
  \$or  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) \$procmux$1061  (
    .A(\$auto$slang_frontend.cc:694:finish$\s_enable_count_lo$272 ),
    .B(\$auto$builder.cc:338:Biop$251 ),
    .Y(\$auto$slang_frontend.cc:694:finish$\s_enable_count_lo$274 )
  );
  /* full_case = 32'd1 */
  /* src = "../rtl/timer_unit/timer_unit.sv:394.5-394.30|../rtl/timer_unit/timer_unit.sv:392.7-411.9" */
  \$mux  #(
    .WIDTH(32'd1)
  ) \$procmux$1067  (
    .A(\$auto$slang_frontend.cc:694:finish$\s_enable_count_prescaler_lo$273 ),
    .B(1'h0),
    .S(\$auto$builder.cc:338:Biop$251 ),
    .Y(\$auto$slang_frontend.cc:694:finish$\s_enable_count_prescaler_lo$275 )
  );
  /* src = "../rtl/timer_unit/timer_unit.sv:392.7-411.9|../rtl/timer_unit/timer_unit.sv:390.2-412.7" */
  \$and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) \$procmux$1072  (
    .A(s_cfg_lo_reg[0]),
    .B(\$auto$slang_frontend.cc:694:finish$\s_enable_count_prescaler_lo$275 ),
    .Y(\$auto$slang_frontend.cc:694:finish$\s_enable_count_prescaler_lo$277 )
  );
  /* src = "../rtl/timer_unit/timer_unit.sv:392.7-411.9|../rtl/timer_unit/timer_unit.sv:390.2-412.7" */
  \$and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) \$procmux$1075  (
    .A(s_cfg_lo_reg[0]),
    .B(\$auto$slang_frontend.cc:694:finish$\s_enable_count_lo$274 ),
    .Y(\$auto$slang_frontend.cc:694:finish$\s_enable_count_lo$276 )
  );
  /* src = "../rtl/timer_unit/timer_unit.sv:376.7-376.41|../rtl/timer_unit/timer_unit.sv:374.2-377.7" */
  \$or  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) \$procmux$1100  (
    .A(\$auto$builder.cc:338:Biop$195 ),
    .B(\$auto$builder.cc:338:Biop$237 ),
    .Y(s_reset_count_prescaler_hi)
  );
  /* src = "../rtl/timer_unit/timer_unit.sv:371.7-371.41|../rtl/timer_unit/timer_unit.sv:369.2-372.7" */
  \$or  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) \$procmux$1105  (
    .A(\$auto$builder.cc:338:Biop$158 ),
    .B(\$auto$builder.cc:338:Biop$230 ),
    .Y(s_reset_count_prescaler_lo)
  );
  /* full_case = 32'd1 */
  /* src = "../rtl/timer_unit/timer_unit.sv:355.5-358.10|../rtl/timer_unit/timer_unit.sv:353.7-366.12" */
  \$mux  #(
    .WIDTH(32'd1)
  ) \$procmux$1121  (
    .A(\$auto$builder.cc:338:Biop$207 ),
    .B(\$auto$builder.cc:338:Biop$183 ),
    .S(s_cfg_lo_reg[31]),
    .Y(\$auto$slang_frontend.cc:694:finish$\s_reset_count_hi$224 )
  );
  /* full_case = 32'd1 */
  /* src = "../rtl/timer_unit/timer_unit.sv:347.4-350.7|../rtl/timer_unit/timer_unit.sv:346.2-367.14" */
  \$or  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) \$procmux$1143  (
    .A(\$auto$slang_frontend.cc:694:finish$\s_reset_count_hi$224 ),
    .B(\$auto$builder.cc:338:Biop$195 ),
    .Y(s_reset_count_hi)
  );
  /* full_case = 32'd1 */
  /* src = "../rtl/timer_unit/timer_unit.sv:332.5-335.10|../rtl/timer_unit/timer_unit.sv:330.7-343.12" */
  \$mux  #(
    .WIDTH(32'd1)
  ) \$procmux$1157  (
    .A(\$auto$builder.cc:338:Biop$170 ),
    .B(\$auto$builder.cc:338:Biop$183 ),
    .S(s_cfg_lo_reg[31]),
    .Y(\$auto$slang_frontend.cc:694:finish$\s_reset_count_lo$187 )
  );
  /* full_case = 32'd1 */
  /* src = "../rtl/timer_unit/timer_unit.sv:324.4-327.7|../rtl/timer_unit/timer_unit.sv:323.2-344.7" */
  \$or  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) \$procmux$1176  (
    .A(\$auto$slang_frontend.cc:694:finish$\s_reset_count_lo$187 ),
    .B(\$auto$builder.cc:338:Biop$158 ),
    .Y(s_reset_count_lo)
  );
  /* src = "../rtl/timer_unit/timer_unit.sv:303.18-303.49|../rtl/timer_unit/timer_unit.sv:285.14-305.21" */
  \$pmux  #(
    .S_WIDTH(32'd6),
    .WIDTH(32'd32)
  ) \$procmux$644  (
    .A(32'd0),
    .B({ s_cfg_lo_reg, s_cfg_hi_reg, s_timer_val_lo, s_timer_val_hi, s_timer_cmp_lo_reg, s_timer_cmp_hi_reg }),
    .S({ \$procmux$650_CMP , \$procmux$649_CMP , \$procmux$648_CMP , \$procmux$647_CMP , \$procmux$646_CMP , \$procmux$645_CMP  }),
    .Y(\$auto$slang_frontend.cc:694:finish$\r_rdata_o$150 )
  );
  /* src = "../rtl/timer_unit/timer_unit.sv:303.18-303.49|../rtl/timer_unit/timer_unit.sv:285.14-305.21" */
  \$eq  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd6),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd5),
    .Y_WIDTH(32'd1)
  ) \$procmux$645_CMP0  (
    .A(s_addr[5:0]),
    .B(5'h14),
    .Y(\$procmux$645_CMP )
  );
  /* src = "../rtl/timer_unit/timer_unit.sv:300.18-300.49|../rtl/timer_unit/timer_unit.sv:285.14-305.21" */
  \$eq  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd6),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd5),
    .Y_WIDTH(32'd1)
  ) \$procmux$646_CMP0  (
    .A(s_addr[5:0]),
    .B(5'h10),
    .Y(\$procmux$646_CMP )
  );
  /* src = "../rtl/timer_unit/timer_unit.sv:297.18-297.45|../rtl/timer_unit/timer_unit.sv:285.14-305.21" */
  \$eq  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd6),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd4),
    .Y_WIDTH(32'd1)
  ) \$procmux$647_CMP0  (
    .A(s_addr[5:0]),
    .B(4'hc),
    .Y(\$procmux$647_CMP )
  );
  /* src = "../rtl/timer_unit/timer_unit.sv:294.18-294.45|../rtl/timer_unit/timer_unit.sv:285.14-305.21" */
  \$eq  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd6),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd4),
    .Y_WIDTH(32'd1)
  ) \$procmux$648_CMP0  (
    .A(s_addr[5:0]),
    .B(4'h8),
    .Y(\$procmux$648_CMP )
  );
  /* src = "../rtl/timer_unit/timer_unit.sv:291.18-291.43|../rtl/timer_unit/timer_unit.sv:285.14-305.21" */
  \$eq  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd6),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd3),
    .Y_WIDTH(32'd1)
  ) \$procmux$649_CMP0  (
    .A(s_addr[5:0]),
    .B(3'h4),
    .Y(\$procmux$649_CMP )
  );
  /* src = "../rtl/timer_unit/timer_unit.sv:288.18-288.43|../rtl/timer_unit/timer_unit.sv:285.14-305.21" */
  \$logic_not  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd6),
    .Y_WIDTH(32'd1)
  ) \$procmux$650_CMP0  (
    .A(s_addr[5:0]),
    .Y(\$procmux$650_CMP )
  );
  /* src = "../rtl/timer_unit/timer_unit.sv:285.14-305.21|../rtl/timer_unit/timer_unit.sv:282.9-307.14" */
  \$mux  #(
    .WIDTH(32'd32)
  ) \$procmux$654  (
    .A(32'd0),
    .B(\$auto$slang_frontend.cc:694:finish$\r_rdata_o$150 ),
    .S(\$auto$builder.cc:338:Biop$147 ),
    .Y(r_rdata_o)
  );
  /* full_case = 32'd1 */
  /* src = "../rtl/timer_unit/timer_unit.sv:474.4-477.7|../rtl/timer_unit/timer_unit.sv:473.2-481.7" */
  \$mux  #(
    .WIDTH(32'd1)
  ) \$procmux$657  (
    .A(\$auto$builder.cc:338:Biop$382 ),
    .B(1'h0),
    .S(s_cfg_lo_reg[31]),
    .Y(irq_hi_o)
  );
  /* src = "../rtl/timer_unit/timer_unit.sv:254.4-254.32|../rtl/timer_unit/timer_unit.sv:253.2-254.32" */
  \$mux  #(
    .WIDTH(32'd1)
  ) \$procmux$662  (
    .A(\$auto$slang_frontend.cc:694:finish$\s_cfg_hi$48 [1]),
    .B(1'h0),
    .S(s_reset_count_hi),
    .Y(s_cfg_hi[1])
  );
  /* src = "../rtl/timer_unit/timer_unit.sv:250.4-250.32|../rtl/timer_unit/timer_unit.sv:249.2-250.32" */
  \$mux  #(
    .WIDTH(32'd1)
  ) \$procmux$668  (
    .A(\$auto$slang_frontend.cc:694:finish$\s_cfg_lo$47 [1]),
    .B(1'h0),
    .S(s_reset_count_lo),
    .Y(s_cfg_lo[1])
  );
  /* src = "../rtl/timer_unit/timer_unit.sv:244.11-244.37|../rtl/timer_unit/timer_unit.sv:243.7-244.37" */
  \$mux  #(
    .WIDTH(32'd1)
  ) \$procmux$673  (
    .A(\$auto$slang_frontend.cc:694:finish$\s_cfg_hi$48 [0]),
    .B(1'h0),
    .S(\$auto$builder.cc:338:Biop$124 ),
    .Y(\$auto$slang_frontend.cc:694:finish$\s_cfg_hi[0]$127 )
  );
  /* full_case = 32'd1 */
  /* src = "../rtl/timer_unit/timer_unit.sv:241.9-241.35|../rtl/timer_unit/timer_unit.sv:240.7-245.9" */
  \$mux  #(
    .WIDTH(32'd1)
  ) \$procmux$685  (
    .A(\$auto$slang_frontend.cc:694:finish$\s_cfg_hi[0]$127 ),
    .B(1'h0),
    .S(\$auto$builder.cc:338:Biop$112 ),
    .Y(\$auto$slang_frontend.cc:694:finish$\s_cfg_hi[0]$128 )
  );
  /* full_case = 32'd1 */
  /* src = "../rtl/timer_unit/timer_unit.sv:237.4-237.30|../rtl/timer_unit/timer_unit.sv:236.2-246.7" */
  \$or  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) \$procmux$694  (
    .A(\$auto$slang_frontend.cc:694:finish$\s_cfg_hi[0]$128 ),
    .B(\$auto$builder.cc:338:Biop$100 ),
    .Y(s_cfg_hi[0])
  );
  /* src = "../rtl/timer_unit/timer_unit.sv:231.7-231.33|../rtl/timer_unit/timer_unit.sv:230.6-231.33" */
  \$mux  #(
    .WIDTH(32'd1)
  ) \$procmux$698  (
    .A(\$auto$slang_frontend.cc:694:finish$\s_cfg_lo$47 [0]),
    .B(1'h0),
    .S(\$auto$builder.cc:338:Biop$124 ),
    .Y(\$auto$slang_frontend.cc:694:finish$\s_cfg_lo[0]$88 )
  );
  /* full_case = 32'd1 */
  /* src = "../rtl/timer_unit/timer_unit.sv:225.5-226.33|../rtl/timer_unit/timer_unit.sv:223.7-232.12" */
  \$mux  #(
    .WIDTH(32'd1)
  ) \$procmux$710  (
    .A(\$auto$slang_frontend.cc:694:finish$\s_cfg_lo[0]$75 ),
    .B(\$auto$slang_frontend.cc:694:finish$\s_cfg_lo[0]$88 ),
    .S(s_cfg_lo_reg[31]),
    .Y(\$auto$slang_frontend.cc:694:finish$\s_cfg_lo[0]$89 )
  );
  /* src = "../rtl/timer_unit/timer_unit.sv:226.7-226.33|../rtl/timer_unit/timer_unit.sv:225.5-226.33" */
  \$mux  #(
    .WIDTH(32'd1)
  ) \$procmux$717  (
    .A(\$auto$slang_frontend.cc:694:finish$\s_cfg_lo$47 [0]),
    .B(1'h0),
    .S(\$auto$builder.cc:338:Biop$120 ),
    .Y(\$auto$slang_frontend.cc:694:finish$\s_cfg_lo[0]$75 )
  );
  /* full_case = 32'd1 */
  /* src = "../rtl/timer_unit/timer_unit.sv:220.4-220.30|../rtl/timer_unit/timer_unit.sv:219.2-233.7" */
  \$or  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) \$procmux$727  (
    .A(\$auto$slang_frontend.cc:694:finish$\s_cfg_lo[0]$89 ),
    .B(\$auto$builder.cc:338:Biop$60 ),
    .Y(s_cfg_lo[0])
  );
  /* src = "../rtl/timer_unit/timer_unit.sv:201.18-201.47|../rtl/timer_unit/timer_unit.sv:183.14-215.21" */
  \$eq  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd6),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd5),
    .Y_WIDTH(32'd1)
  ) \$procmux$735_CMP0  (
    .A(addr_i[5:0]),
    .B(5'h14),
    .Y(\$procmux$735_CMP )
  );
  /* src = "../rtl/timer_unit/timer_unit.sv:198.18-198.47|../rtl/timer_unit/timer_unit.sv:183.14-215.21" */
  \$eq  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd6),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd5),
    .Y_WIDTH(32'd1)
  ) \$procmux$744_CMP0  (
    .A(addr_i[5:0]),
    .B(5'h10),
    .Y(\$procmux$744_CMP )
  );
  /* src = "../rtl/timer_unit/timer_unit.sv:189.4-189.33|../rtl/timer_unit/timer_unit.sv:183.14-215.21" */
  \$mux  #(
    .WIDTH(32'd32)
  ) \$procmux$755  (
    .A({ s_cfg_hi_reg[31:2], 1'hx, s_cfg_hi_reg[0] }),
    .B(wdata_i),
    .S(\$procmux$756_CMP ),
    .Y(\$auto$slang_frontend.cc:694:finish$\s_cfg_hi$38 )
  );
  /* src = "../rtl/timer_unit/timer_unit.sv:189.4-189.33|../rtl/timer_unit/timer_unit.sv:183.14-215.21" */
  \$eq  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd6),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd3),
    .Y_WIDTH(32'd1)
  ) \$procmux$756_CMP0  (
    .A(addr_i[5:0]),
    .B(3'h4),
    .Y(\$procmux$756_CMP )
  );
  /* src = "../rtl/timer_unit/timer_unit.sv:186.4-186.33|../rtl/timer_unit/timer_unit.sv:183.14-215.21" */
  \$mux  #(
    .WIDTH(32'd32)
  ) \$procmux$768  (
    .A({ s_cfg_lo_reg[31:2], 1'hx, s_cfg_lo_reg[0] }),
    .B(wdata_i),
    .S(\$procmux$769_CMP ),
    .Y(\$auto$slang_frontend.cc:694:finish$\s_cfg_lo$37 )
  );
  /* src = "../rtl/timer_unit/timer_unit.sv:186.4-186.33|../rtl/timer_unit/timer_unit.sv:183.14-215.21" */
  \$logic_not  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd6),
    .Y_WIDTH(32'd1)
  ) \$procmux$769_CMP0  (
    .A(addr_i[5:0]),
    .Y(\$procmux$769_CMP )
  );
  /* src = "../rtl/timer_unit/timer_unit.sv:213.4-213.30|../rtl/timer_unit/timer_unit.sv:183.14-215.21" */
  \$eq  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd6),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd6),
    .Y_WIDTH(32'd1)
  ) \$procmux$773_CMP0  (
    .A(addr_i[5:0]),
    .B(6'h24),
    .Y(\$auto$slang_frontend.cc:694:finish$\s_reset_timer_hi$36 )
  );
  /* src = "../rtl/timer_unit/timer_unit.sv:210.4-210.30|../rtl/timer_unit/timer_unit.sv:183.14-215.21" */
  \$eq  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd6),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd6),
    .Y_WIDTH(32'd1)
  ) \$procmux$778_CMP0  (
    .A(addr_i[5:0]),
    .B(6'h20),
    .Y(\$auto$slang_frontend.cc:694:finish$\s_reset_timer_lo$35 )
  );
  /* src = "../rtl/timer_unit/timer_unit.sv:207.4-207.30|../rtl/timer_unit/timer_unit.sv:183.14-215.21" */
  \$eq  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd6),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd5),
    .Y_WIDTH(32'd1)
  ) \$procmux$784_CMP0  (
    .A(addr_i[5:0]),
    .B(5'h1c),
    .Y(\$auto$slang_frontend.cc:694:finish$\s_start_timer_hi$34 )
  );
  /* src = "../rtl/timer_unit/timer_unit.sv:204.4-204.30|../rtl/timer_unit/timer_unit.sv:183.14-215.21" */
  \$eq  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd6),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd5),
    .Y_WIDTH(32'd1)
  ) \$procmux$791_CMP0  (
    .A(addr_i[5:0]),
    .B(5'h18),
    .Y(\$auto$slang_frontend.cc:694:finish$\s_start_timer_lo$33 )
  );
  /* src = "../rtl/timer_unit/timer_unit.sv:195.4-195.30|../rtl/timer_unit/timer_unit.sv:183.14-215.21" */
  \$eq  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd6),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd4),
    .Y_WIDTH(32'd1)
  ) \$procmux$801_CMP0  (
    .A(addr_i[5:0]),
    .B(4'hc),
    .Y(\$auto$slang_frontend.cc:694:finish$\s_write_counter_hi$32 )
  );
  /* src = "../rtl/timer_unit/timer_unit.sv:192.4-192.30|../rtl/timer_unit/timer_unit.sv:183.14-215.21" */
  \$eq  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd6),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd4),
    .Y_WIDTH(32'd1)
  ) \$procmux$812_CMP0  (
    .A(addr_i[5:0]),
    .B(4'h8),
    .Y(\$auto$slang_frontend.cc:694:finish$\s_write_counter_lo$31 )
  );
  /* src = "../rtl/timer_unit/timer_unit.sv:183.14-215.21|../rtl/timer_unit/timer_unit.sv:180.9-216.14" */
  \$mux  #(
    .WIDTH(32'd32)
  ) \$procmux$822  (
    .A({ s_cfg_hi_reg[31:2], 1'hx, s_cfg_hi_reg[0] }),
    .B(\$auto$slang_frontend.cc:694:finish$\s_cfg_hi$38 ),
    .S(\$auto$builder.cc:338:Biop$28 ),
    .Y({ s_cfg_hi[31:2], \$auto$slang_frontend.cc:694:finish$\s_cfg_hi$48 [1:0] })
  );
  /* src = "../rtl/timer_unit/timer_unit.sv:183.14-215.21|../rtl/timer_unit/timer_unit.sv:180.9-216.14" */
  \$mux  #(
    .WIDTH(32'd32)
  ) \$procmux$825  (
    .A({ s_cfg_lo_reg[31:2], 1'hx, s_cfg_lo_reg[0] }),
    .B(\$auto$slang_frontend.cc:694:finish$\s_cfg_lo$37 ),
    .S(\$auto$builder.cc:338:Biop$28 ),
    .Y({ s_cfg_lo[31:2], \$auto$slang_frontend.cc:694:finish$\s_cfg_lo$47 [1:0] })
  );
  /* src = "../rtl/timer_unit/timer_unit.sv:183.14-215.21|../rtl/timer_unit/timer_unit.sv:180.9-216.14" */
  \$and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) \$procmux$828  (
    .A(\$auto$builder.cc:338:Biop$28 ),
    .B(\$auto$slang_frontend.cc:694:finish$\s_reset_timer_hi$36 ),
    .Y(s_reset_timer_hi)
  );
  /* src = "../rtl/timer_unit/timer_unit.sv:183.14-215.21|../rtl/timer_unit/timer_unit.sv:180.9-216.14" */
  \$and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) \$procmux$831  (
    .A(\$auto$builder.cc:338:Biop$28 ),
    .B(\$auto$slang_frontend.cc:694:finish$\s_reset_timer_lo$35 ),
    .Y(s_reset_timer_lo)
  );
  /* src = "../rtl/timer_unit/timer_unit.sv:183.14-215.21|../rtl/timer_unit/timer_unit.sv:180.9-216.14" */
  \$and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) \$procmux$834  (
    .A(\$auto$builder.cc:338:Biop$28 ),
    .B(\$auto$slang_frontend.cc:694:finish$\s_start_timer_hi$34 ),
    .Y(s_start_timer_hi)
  );
  /* src = "../rtl/timer_unit/timer_unit.sv:183.14-215.21|../rtl/timer_unit/timer_unit.sv:180.9-216.14" */
  \$and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) \$procmux$837  (
    .A(\$auto$builder.cc:338:Biop$28 ),
    .B(\$auto$slang_frontend.cc:694:finish$\s_start_timer_lo$33 ),
    .Y(s_start_timer_lo)
  );
  /* src = "../rtl/timer_unit/timer_unit.sv:183.14-215.21|../rtl/timer_unit/timer_unit.sv:180.9-216.14" */
  \$and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) \$procmux$840  (
    .A(\$auto$builder.cc:338:Biop$28 ),
    .B(\$auto$slang_frontend.cc:694:finish$\s_write_counter_hi$32 ),
    .Y(s_write_counter_hi)
  );
  /* src = "../rtl/timer_unit/timer_unit.sv:183.14-215.21|../rtl/timer_unit/timer_unit.sv:180.9-216.14" */
  \$and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) \$procmux$843  (
    .A(\$auto$builder.cc:338:Biop$28 ),
    .B(\$auto$slang_frontend.cc:694:finish$\s_write_counter_lo$31 ),
    .Y(s_write_counter_lo)
  );
  /* full_case = 32'd1 */
  /* src = "../rtl/timer_unit/timer_unit.sv:453.3-457.6|../rtl/timer_unit/timer_unit.sv:452.14-463.6" */
  \$mux  #(
    .WIDTH(32'd1)
  ) \$procmux$846  (
    .A(1'h1),
    .B(s_ref_clk_edge),
    .S(\$auto$builder.cc:338:Biop$267 ),
    .Y(\$auto$slang_frontend.cc:694:finish$\s_enable_count_prescaler_lo$271 )
  );
  /* full_case = 32'd1 */
  /* src = "../rtl/timer_unit/timer_unit.sv:448.3-451.6|../rtl/timer_unit/timer_unit.sv:447.11-463.6" */
  \$mux  #(
    .WIDTH(32'd1)
  ) \$procmux$896  (
    .A(s_target_reached_prescaler_lo),
    .B(s_ref_clk_edge),
    .S(\$auto$builder.cc:338:Biop$259 ),
    .Y(\$auto$slang_frontend.cc:694:finish$\s_enable_count_lo$272 )
  );
  /* full_case = 32'd1 */
  /* src = "../rtl/timer_unit/timer_unit.sv:448.3-451.6|../rtl/timer_unit/timer_unit.sv:447.11-463.6" */
  \$mux  #(
    .WIDTH(32'd1)
  ) \$procmux$907  (
    .A(\$auto$slang_frontend.cc:694:finish$\s_enable_count_prescaler_lo$271 ),
    .B(\$auto$slang_frontend.cc:694:finish$\s_enable_count_prescaler_lo$277 ),
    .S(\$auto$builder.cc:338:Biop$259 ),
    .Y(\$auto$slang_frontend.cc:694:finish$\s_enable_count_prescaler_lo$367 )
  );
  /* full_case = 32'd1 */
  /* src = "../rtl/timer_unit/timer_unit.sv:443.6-446.9|../rtl/timer_unit/timer_unit.sv:442.6-463.6" */
  \$mux  #(
    .WIDTH(32'd1)
  ) \$procmux$918  (
    .A(\$auto$opt_share.cc:222:merge_operators$1217 ),
    .B(\$auto$builder.cc:338:Biop$331 ),
    .S(\$auto$builder.cc:338:Biop$251 ),
    .Y(\$auto$slang_frontend.cc:694:finish$\s_enable_count_hi$369 )
  );
  /* full_case = 32'd1 */
  /* src = "../rtl/timer_unit/timer_unit.sv:443.6-446.9|../rtl/timer_unit/timer_unit.sv:442.6-463.6" */
  \$mux  #(
    .WIDTH(32'd1)
  ) \$procmux$934  (
    .A(\$auto$slang_frontend.cc:694:finish$\s_enable_count_prescaler_lo$367 ),
    .B(\$auto$slang_frontend.cc:694:finish$\s_enable_count_prescaler_lo$277 ),
    .S(\$auto$builder.cc:338:Biop$251 ),
    .Y(\$auto$slang_frontend.cc:694:finish$\s_enable_count_prescaler_lo$370 )
  );
  /* src = "../rtl/timer_unit/timer_unit.sv:442.6-463.6|../rtl/timer_unit/timer_unit.sv:440.2-464.7" */
  \$mux  #(
    .WIDTH(32'd1)
  ) \$procmux$941  (
    .A(\$auto$slang_frontend.cc:694:finish$\s_enable_count_prescaler_lo$277 ),
    .B(\$auto$slang_frontend.cc:694:finish$\s_enable_count_prescaler_lo$370 ),
    .S(\$auto$builder.cc:338:Biop$319 ),
    .Y(s_enable_count_prescaler_lo)
  );
  /* src = "../rtl/timer_unit/timer_unit.sv:442.6-463.6|../rtl/timer_unit/timer_unit.sv:440.2-464.7" */
  \$mux  #(
    .WIDTH(32'd1)
  ) \$procmux$946  (
    .A(\$auto$slang_frontend.cc:694:finish$\s_enable_count_hi$312 ),
    .B(\$auto$slang_frontend.cc:694:finish$\s_enable_count_hi$369 ),
    .S(\$auto$builder.cc:338:Biop$319 ),
    .Y(s_enable_count_hi)
  );
  /* src = "../rtl/timer_unit/timer_unit.sv:442.6-463.6|../rtl/timer_unit/timer_unit.sv:440.2-464.7" */
  \$mux  #(
    .WIDTH(32'd1)
  ) \$procmux$951  (
    .A(\$auto$slang_frontend.cc:694:finish$\s_enable_count_lo$276 ),
    .B(\$auto$slang_frontend.cc:694:finish$\s_enable_count_lo$274 ),
    .S(\$auto$builder.cc:338:Biop$319 ),
    .Y(s_enable_count_lo)
  );
  /* full_case = 32'd1 */
  /* src = "../rtl/timer_unit/timer_unit.sv:428.6-431.9|../rtl/timer_unit/timer_unit.sv:427.4-436.9" */
  \$mux  #(
    .WIDTH(32'd1)
  ) \$procmux$956  (
    .A(1'h1),
    .B(s_ref_clk_edge),
    .S(\$auto$builder.cc:338:Biop$303 ),
    .Y(\$auto$slang_frontend.cc:694:finish$\s_enable_count_prescaler_hi$307 )
  );
  /* full_case = 32'd1 */
  /* src = "../rtl/timer_unit/timer_unit.sv:424.7-424.42|../rtl/timer_unit/timer_unit.sv:422.9-436.9" */
  \$mux  #(
    .WIDTH(32'd1)
  ) \$procmux$980  (
    .A(s_target_reached_prescaler_hi),
    .B(s_ref_clk_edge),
    .S(\$auto$builder.cc:338:Biop$295 ),
    .Y(\$auto$slang_frontend.cc:694:finish$\s_enable_count_hi$308 )
  );
  /* full_case = 32'd1 */
  /* src = "../rtl/timer_unit/timer_unit.sv:424.7-424.42|../rtl/timer_unit/timer_unit.sv:422.9-436.9" */
  \$mux  #(
    .WIDTH(32'd1)
  ) \$procmux$990  (
    .A(\$auto$slang_frontend.cc:694:finish$\s_enable_count_prescaler_hi$307 ),
    .B(1'h0),
    .S(\$auto$builder.cc:338:Biop$295 ),
    .Y(\$auto$slang_frontend.cc:694:finish$\s_enable_count_prescaler_hi$309 )
  );
  /* src = "../rtl/timer_unit/timer_unit.sv:561.23" */
  \timer_unit_counter$timer_unit.counter_hi_i  counter_hi_i (
    .clk_i(clk_i),
    .compare_value_i(s_timer_cmp_hi_reg),
    .counter_value_i(wdata_i),
    .counter_value_o(s_timer_val_hi),
    .enable_count_i(s_enable_count_hi),
    .reset_count_i(s_reset_count_hi),
    .rst_ni(rst_ni),
    .target_reached_o(s_target_reached_hi),
    .write_counter_i(s_write_counter_hi)
  );
  /* src = "../rtl/timer_unit/timer_unit.sv:545.23" */
  \timer_unit_counter$timer_unit.counter_lo_i  counter_lo_i (
    .clk_i(clk_i),
    .compare_value_i(s_timer_cmp_lo_reg),
    .counter_value_i(wdata_i),
    .counter_value_o(s_timer_val_lo),
    .enable_count_i(s_enable_count_lo),
    .reset_count_i(s_reset_count_lo),
    .rst_ni(rst_ni),
    .target_reached_o(s_target_reached_lo),
    .write_counter_i(s_write_counter_lo)
  );
  /* src = "../rtl/timer_unit/timer_unit.sv:529.29" */
  \timer_unit_counter_presc$timer_unit.prescaler_hi_i  prescaler_hi_i (
    .clk_i(clk_i),
    .compare_value_i({ 24'h000000, s_cfg_hi_reg[15:8] }),
    .counter_value_i(32'd0),
    .enable_count_i(s_enable_count_prescaler_hi),
    .reset_count_i(s_reset_count_prescaler_hi),
    .rst_ni(rst_ni),
    .target_reached_o(s_target_reached_prescaler_hi),
    .write_counter_i(1'h0)
  );
  /* src = "../rtl/timer_unit/timer_unit.sv:513.29" */
  \timer_unit_counter_presc$timer_unit.prescaler_lo_i  prescaler_lo_i (
    .clk_i(clk_i),
    .compare_value_i({ 24'h000000, s_cfg_lo_reg[15:8] }),
    .counter_value_i(32'd0),
    .enable_count_i(s_enable_count_prescaler_lo),
    .reset_count_i(s_reset_count_prescaler_lo),
    .rst_ni(rst_ni),
    .target_reached_o(s_target_reached_prescaler_lo),
    .write_counter_i(1'h0)
  );
  assign \$auto$slang_frontend.cc:694:finish$\s_cfg_hi$48 [31:2] = s_cfg_hi[31:2];
  assign \$auto$slang_frontend.cc:694:finish$\s_cfg_lo$47 [31:2] = s_cfg_lo[31:2];
  assign CS[1] = 1'h0;
  assign NS = req_i;
  assign gnt_o = 1'h1;
  assign r_opc_o = 1'h0;
  assign r_valid_o = CS[0];
  assign s_req = CS[0];
endmodule

/* src = "../rtl/timer_unit/timer_unit_counter.sv:13.8" */
module \timer_unit_counter$timer_unit.counter_hi_i (clk_i, rst_ni, write_counter_i, counter_value_i, reset_count_i, enable_count_i, compare_value_i, target_reached_o, counter_value_o);
  wire [31:0] \$auto$builder.cc:338:Biop$537 ;
  wire \$auto$builder.cc:338:Biop$552 ;
  /* src = "../rtl/timer_unit/timer_unit_counter.sv:45.3-46.31" */
  wire [31:0] \$auto$slang_frontend.cc:694:finish$\s_count$538 ;
  /* src = "../rtl/timer_unit/timer_unit_counter.sv:41.5-47.10" */
  wire [31:0] \$auto$slang_frontend.cc:694:finish$\s_count$539 ;
  /* src = "../rtl/timer_unit/timer_unit_counter.sv:15.24" */
  input clk_i;
  wire clk_i;
  /* src = "../rtl/timer_unit/timer_unit_counter.sv:23.24" */
  input [31:0] compare_value_i;
  wire [31:0] compare_value_i;
  /* src = "../rtl/timer_unit/timer_unit_counter.sv:19.24" */
  input [31:0] counter_value_i;
  wire [31:0] counter_value_i;
  /* src = "../rtl/timer_unit/timer_unit_counter.sv:25.24" */
  output [31:0] counter_value_o;
  wire [31:0] counter_value_o;
  /* src = "../rtl/timer_unit/timer_unit_counter.sv:22.24" */
  input enable_count_i;
  wire enable_count_i;
  /* src = "../rtl/timer_unit/timer_unit_counter.sv:21.24" */
  input reset_count_i;
  wire reset_count_i;
  /* src = "../rtl/timer_unit/timer_unit_counter.sv:16.24" */
  input rst_ni;
  wire rst_ni;
  /* src = "../rtl/timer_unit/timer_unit_counter.sv:29.24" */
  wire [31:0] s_count;
  /* src = "../rtl/timer_unit/timer_unit_counter.sv:29.33" */
  wire [31:0] s_count_reg;
  /* src = "../rtl/timer_unit/timer_unit_counter.sv:26.24" */
  output target_reached_o;
  wire target_reached_o;
  /* src = "../rtl/timer_unit/timer_unit_counter.sv:18.24" */
  input write_counter_i;
  wire write_counter_i;
  \$add  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd32),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd32)
  ) \$auto$builder.cc:330:Biop$536  (
    .A(s_count_reg),
    .B(1'h1),
    .Y(\$auto$builder.cc:338:Biop$537 )
  );
  \$eq  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd32),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd32),
    .Y_WIDTH(32'd1)
  ) \$auto$builder.cc:330:Biop$551  (
    .A(s_count),
    .B(compare_value_i),
    .Y(\$auto$builder.cc:338:Biop$552 )
  );
  /* src = "../rtl/timer_unit/timer_unit_counter.sv:51.4" */
  \$adff  #(
    .ARST_POLARITY(32'd0),
    .ARST_VALUE(32'd0),
    .CLK_POLARITY(32'd1),
    .WIDTH(32'd32)
  ) \$driver$s_count_reg  (
    .ARST(rst_ni),
    .CLK(clk_i),
    .D(s_count),
    .Q(s_count_reg)
  );
  /* src = "../rtl/timer_unit/timer_unit_counter.sv:60.4" */
  \$adff  #(
    .ARST_POLARITY(32'd0),
    .ARST_VALUE(1'h0),
    .CLK_POLARITY(32'd1),
    .WIDTH(32'd1)
  ) \$driver$target_reached_o  (
    .ARST(rst_ni),
    .CLK(clk_i),
    .D(\$auto$builder.cc:338:Biop$552 ),
    .Q(target_reached_o)
  );
  /* src = "../rtl/timer_unit/timer_unit_counter.sv:46.5-46.31|../rtl/timer_unit/timer_unit_counter.sv:45.3-46.31" */
  \$mux  #(
    .WIDTH(32'd32)
  ) \$procmux$559  (
    .A(s_count_reg),
    .B(\$auto$builder.cc:338:Biop$537 ),
    .S(enable_count_i),
    .Y(\$auto$slang_frontend.cc:694:finish$\s_count$538 )
  );
  /* full_case = 32'd1 */
  /* src = "../rtl/timer_unit/timer_unit_counter.sv:42.7-42.33|../rtl/timer_unit/timer_unit_counter.sv:41.5-47.10" */
  \$mux  #(
    .WIDTH(32'd32)
  ) \$procmux$569  (
    .A(\$auto$slang_frontend.cc:694:finish$\s_count$538 ),
    .B(counter_value_i),
    .S(write_counter_i),
    .Y(\$auto$slang_frontend.cc:694:finish$\s_count$539 )
  );
  /* full_case = 32'd1 */
  /* src = "../rtl/timer_unit/timer_unit_counter.sv:38.10-38.22|../rtl/timer_unit/timer_unit_counter.sv:37.7-48.5" */
  \$mux  #(
    .WIDTH(32'd32)
  ) \$procmux$576  (
    .A(\$auto$slang_frontend.cc:694:finish$\s_count$539 ),
    .B(32'd0),
    .S(reset_count_i),
    .Y(s_count)
  );
  assign counter_value_o = s_count_reg;
endmodule

/* src = "../rtl/timer_unit/timer_unit_counter.sv:13.8" */
module \timer_unit_counter$timer_unit.counter_lo_i (clk_i, rst_ni, write_counter_i, counter_value_i, reset_count_i, enable_count_i, compare_value_i, target_reached_o, counter_value_o);
  wire [31:0] \$auto$builder.cc:338:Biop$504 ;
  wire \$auto$builder.cc:338:Biop$519 ;
  /* src = "../rtl/timer_unit/timer_unit_counter.sv:45.3-46.31" */
  wire [31:0] \$auto$slang_frontend.cc:694:finish$\s_count$505 ;
  /* src = "../rtl/timer_unit/timer_unit_counter.sv:41.5-47.10" */
  wire [31:0] \$auto$slang_frontend.cc:694:finish$\s_count$506 ;
  /* src = "../rtl/timer_unit/timer_unit_counter.sv:15.24" */
  input clk_i;
  wire clk_i;
  /* src = "../rtl/timer_unit/timer_unit_counter.sv:23.24" */
  input [31:0] compare_value_i;
  wire [31:0] compare_value_i;
  /* src = "../rtl/timer_unit/timer_unit_counter.sv:19.24" */
  input [31:0] counter_value_i;
  wire [31:0] counter_value_i;
  /* src = "../rtl/timer_unit/timer_unit_counter.sv:25.24" */
  output [31:0] counter_value_o;
  wire [31:0] counter_value_o;
  /* src = "../rtl/timer_unit/timer_unit_counter.sv:22.24" */
  input enable_count_i;
  wire enable_count_i;
  /* src = "../rtl/timer_unit/timer_unit_counter.sv:21.24" */
  input reset_count_i;
  wire reset_count_i;
  /* src = "../rtl/timer_unit/timer_unit_counter.sv:16.24" */
  input rst_ni;
  wire rst_ni;
  /* src = "../rtl/timer_unit/timer_unit_counter.sv:29.24" */
  wire [31:0] s_count;
  /* src = "../rtl/timer_unit/timer_unit_counter.sv:29.33" */
  wire [31:0] s_count_reg;
  /* src = "../rtl/timer_unit/timer_unit_counter.sv:26.24" */
  output target_reached_o;
  wire target_reached_o;
  /* src = "../rtl/timer_unit/timer_unit_counter.sv:18.24" */
  input write_counter_i;
  wire write_counter_i;
  \$add  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd32),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd32)
  ) \$auto$builder.cc:330:Biop$503  (
    .A(s_count_reg),
    .B(1'h1),
    .Y(\$auto$builder.cc:338:Biop$504 )
  );
  \$eq  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd32),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd32),
    .Y_WIDTH(32'd1)
  ) \$auto$builder.cc:330:Biop$518  (
    .A(s_count),
    .B(compare_value_i),
    .Y(\$auto$builder.cc:338:Biop$519 )
  );
  /* src = "../rtl/timer_unit/timer_unit_counter.sv:51.4" */
  \$adff  #(
    .ARST_POLARITY(32'd0),
    .ARST_VALUE(32'd0),
    .CLK_POLARITY(32'd1),
    .WIDTH(32'd32)
  ) \$driver$s_count_reg  (
    .ARST(rst_ni),
    .CLK(clk_i),
    .D(s_count),
    .Q(s_count_reg)
  );
  /* src = "../rtl/timer_unit/timer_unit_counter.sv:60.4" */
  \$adff  #(
    .ARST_POLARITY(32'd0),
    .ARST_VALUE(1'h0),
    .CLK_POLARITY(32'd1),
    .WIDTH(32'd1)
  ) \$driver$target_reached_o  (
    .ARST(rst_ni),
    .CLK(clk_i),
    .D(\$auto$builder.cc:338:Biop$519 ),
    .Q(target_reached_o)
  );
  /* src = "../rtl/timer_unit/timer_unit_counter.sv:46.5-46.31|../rtl/timer_unit/timer_unit_counter.sv:45.3-46.31" */
  \$mux  #(
    .WIDTH(32'd32)
  ) \$procmux$581  (
    .A(s_count_reg),
    .B(\$auto$builder.cc:338:Biop$504 ),
    .S(enable_count_i),
    .Y(\$auto$slang_frontend.cc:694:finish$\s_count$505 )
  );
  /* full_case = 32'd1 */
  /* src = "../rtl/timer_unit/timer_unit_counter.sv:42.7-42.33|../rtl/timer_unit/timer_unit_counter.sv:41.5-47.10" */
  \$mux  #(
    .WIDTH(32'd32)
  ) \$procmux$591  (
    .A(\$auto$slang_frontend.cc:694:finish$\s_count$505 ),
    .B(counter_value_i),
    .S(write_counter_i),
    .Y(\$auto$slang_frontend.cc:694:finish$\s_count$506 )
  );
  /* full_case = 32'd1 */
  /* src = "../rtl/timer_unit/timer_unit_counter.sv:38.10-38.22|../rtl/timer_unit/timer_unit_counter.sv:37.7-48.5" */
  \$mux  #(
    .WIDTH(32'd32)
  ) \$procmux$598  (
    .A(\$auto$slang_frontend.cc:694:finish$\s_count$506 ),
    .B(32'd0),
    .S(reset_count_i),
    .Y(s_count)
  );
  assign counter_value_o = s_count_reg;
endmodule

/* src = "../rtl/timer_unit/timer_unit_counter_presc.sv:13.8" */
module \timer_unit_counter_presc$timer_unit.prescaler_hi_i (clk_i, rst_ni, write_counter_i, counter_value_i, reset_count_i, enable_count_i, compare_value_i, target_reached_o, counter_value_o);
  wire \$auto$builder.cc:338:Biop$459 ;
  wire [31:0] \$auto$builder.cc:338:Biop$471 ;
  wire \$auto$builder.cc:338:Biop$486 ;
  /* src = "../rtl/timer_unit/timer_unit_counter_presc.sv:45.14-46.42" */
  wire [31:0] \$auto$slang_frontend.cc:694:finish$\s_count$472 ;
  /* src = "../rtl/timer_unit/timer_unit_counter_presc.sv:41.9-47.12" */
  wire [31:0] \$auto$slang_frontend.cc:694:finish$\s_count$473 ;
  /* src = "../rtl/timer_unit/timer_unit_counter_presc.sv:15.24" */
  input clk_i;
  wire clk_i;
  /* src = "../rtl/timer_unit/timer_unit_counter_presc.sv:23.24" */
  input [31:0] compare_value_i;
  wire [31:0] compare_value_i;
  /* src = "../rtl/timer_unit/timer_unit_counter_presc.sv:19.24" */
  input [31:0] counter_value_i;
  wire [31:0] counter_value_i;
  /* src = "../rtl/timer_unit/timer_unit_counter_presc.sv:25.24" */
  output [31:0] counter_value_o;
  wire [31:0] counter_value_o;
  /* src = "../rtl/timer_unit/timer_unit_counter_presc.sv:22.24" */
  input enable_count_i;
  wire enable_count_i;
  /* src = "../rtl/timer_unit/timer_unit_counter_presc.sv:21.24" */
  input reset_count_i;
  wire reset_count_i;
  /* src = "../rtl/timer_unit/timer_unit_counter_presc.sv:16.24" */
  input rst_ni;
  wire rst_ni;
  /* src = "../rtl/timer_unit/timer_unit_counter_presc.sv:29.24" */
  wire [31:0] s_count;
  /* src = "../rtl/timer_unit/timer_unit_counter_presc.sv:29.33" */
  wire [31:0] s_count_reg;
  /* src = "../rtl/timer_unit/timer_unit_counter_presc.sv:26.24" */
  output target_reached_o;
  wire target_reached_o;
  /* src = "../rtl/timer_unit/timer_unit_counter_presc.sv:18.24" */
  input write_counter_i;
  wire write_counter_i;
  \$logic_or  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) \$auto$builder.cc:330:Biop$458  (
    .A(reset_count_i),
    .B(target_reached_o),
    .Y(\$auto$builder.cc:338:Biop$459 )
  );
  \$add  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd32),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd32)
  ) \$auto$builder.cc:330:Biop$470  (
    .A(s_count_reg),
    .B(1'h1),
    .Y(\$auto$builder.cc:338:Biop$471 )
  );
  \$eq  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd32),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd32),
    .Y_WIDTH(32'd1)
  ) \$auto$builder.cc:330:Biop$485  (
    .A(s_count),
    .B(compare_value_i),
    .Y(\$auto$builder.cc:338:Biop$486 )
  );
  /* src = "../rtl/timer_unit/timer_unit_counter_presc.sv:51.4" */
  \$adff  #(
    .ARST_POLARITY(32'd0),
    .ARST_VALUE(32'd0),
    .CLK_POLARITY(32'd1),
    .WIDTH(32'd32)
  ) \$driver$s_count_reg  (
    .ARST(rst_ni),
    .CLK(clk_i),
    .D(s_count),
    .Q(s_count_reg)
  );
  /* src = "../rtl/timer_unit/timer_unit_counter_presc.sv:60.4" */
  \$adff  #(
    .ARST_POLARITY(32'd0),
    .ARST_VALUE(1'h0),
    .CLK_POLARITY(32'd1),
    .WIDTH(32'd1)
  ) \$driver$target_reached_o  (
    .ARST(rst_ni),
    .CLK(clk_i),
    .D(\$auto$builder.cc:338:Biop$486 ),
    .Q(target_reached_o)
  );
  /* src = "../rtl/timer_unit/timer_unit_counter_presc.sv:46.16-46.42|../rtl/timer_unit/timer_unit_counter_presc.sv:45.14-46.42" */
  \$mux  #(
    .WIDTH(32'd32)
  ) \$procmux$603  (
    .A(s_count_reg),
    .B(\$auto$builder.cc:338:Biop$471 ),
    .S(enable_count_i),
    .Y(\$auto$slang_frontend.cc:694:finish$\s_count$472 )
  );
  /* full_case = 32'd1 */
  /* src = "../rtl/timer_unit/timer_unit_counter_presc.sv:42.12-42.38|../rtl/timer_unit/timer_unit_counter_presc.sv:41.9-47.12" */
  \$mux  #(
    .WIDTH(32'd32)
  ) \$procmux$613  (
    .A(\$auto$slang_frontend.cc:694:finish$\s_count$472 ),
    .B(counter_value_i),
    .S(write_counter_i),
    .Y(\$auto$slang_frontend.cc:694:finish$\s_count$473 )
  );
  /* full_case = 32'd1 */
  /* src = "../rtl/timer_unit/timer_unit_counter_presc.sv:38.8-38.20|../rtl/timer_unit/timer_unit_counter_presc.sv:37.6-48.9" */
  \$mux  #(
    .WIDTH(32'd32)
  ) \$procmux$620  (
    .A(\$auto$slang_frontend.cc:694:finish$\s_count$473 ),
    .B(32'd0),
    .S(\$auto$builder.cc:338:Biop$459 ),
    .Y(s_count)
  );
  assign counter_value_o = s_count_reg;
endmodule

/* src = "../rtl/timer_unit/timer_unit_counter_presc.sv:13.8" */
module \timer_unit_counter_presc$timer_unit.prescaler_lo_i (clk_i, rst_ni, write_counter_i, counter_value_i, reset_count_i, enable_count_i, compare_value_i, target_reached_o, counter_value_o);
  wire \$auto$builder.cc:338:Biop$422 ;
  wire [31:0] \$auto$builder.cc:338:Biop$434 ;
  wire \$auto$builder.cc:338:Biop$449 ;
  /* src = "../rtl/timer_unit/timer_unit_counter_presc.sv:45.14-46.42" */
  wire [31:0] \$auto$slang_frontend.cc:694:finish$\s_count$435 ;
  /* src = "../rtl/timer_unit/timer_unit_counter_presc.sv:41.9-47.12" */
  wire [31:0] \$auto$slang_frontend.cc:694:finish$\s_count$436 ;
  /* src = "../rtl/timer_unit/timer_unit_counter_presc.sv:15.24" */
  input clk_i;
  wire clk_i;
  /* src = "../rtl/timer_unit/timer_unit_counter_presc.sv:23.24" */
  input [31:0] compare_value_i;
  wire [31:0] compare_value_i;
  /* src = "../rtl/timer_unit/timer_unit_counter_presc.sv:19.24" */
  input [31:0] counter_value_i;
  wire [31:0] counter_value_i;
  /* src = "../rtl/timer_unit/timer_unit_counter_presc.sv:25.24" */
  output [31:0] counter_value_o;
  wire [31:0] counter_value_o;
  /* src = "../rtl/timer_unit/timer_unit_counter_presc.sv:22.24" */
  input enable_count_i;
  wire enable_count_i;
  /* src = "../rtl/timer_unit/timer_unit_counter_presc.sv:21.24" */
  input reset_count_i;
  wire reset_count_i;
  /* src = "../rtl/timer_unit/timer_unit_counter_presc.sv:16.24" */
  input rst_ni;
  wire rst_ni;
  /* src = "../rtl/timer_unit/timer_unit_counter_presc.sv:29.24" */
  wire [31:0] s_count;
  /* src = "../rtl/timer_unit/timer_unit_counter_presc.sv:29.33" */
  wire [31:0] s_count_reg;
  /* src = "../rtl/timer_unit/timer_unit_counter_presc.sv:26.24" */
  output target_reached_o;
  wire target_reached_o;
  /* src = "../rtl/timer_unit/timer_unit_counter_presc.sv:18.24" */
  input write_counter_i;
  wire write_counter_i;
  \$logic_or  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) \$auto$builder.cc:330:Biop$421  (
    .A(reset_count_i),
    .B(target_reached_o),
    .Y(\$auto$builder.cc:338:Biop$422 )
  );
  \$add  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd32),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd32)
  ) \$auto$builder.cc:330:Biop$433  (
    .A(s_count_reg),
    .B(1'h1),
    .Y(\$auto$builder.cc:338:Biop$434 )
  );
  \$eq  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd32),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd32),
    .Y_WIDTH(32'd1)
  ) \$auto$builder.cc:330:Biop$448  (
    .A(s_count),
    .B(compare_value_i),
    .Y(\$auto$builder.cc:338:Biop$449 )
  );
  /* src = "../rtl/timer_unit/timer_unit_counter_presc.sv:51.4" */
  \$adff  #(
    .ARST_POLARITY(32'd0),
    .ARST_VALUE(32'd0),
    .CLK_POLARITY(32'd1),
    .WIDTH(32'd32)
  ) \$driver$s_count_reg  (
    .ARST(rst_ni),
    .CLK(clk_i),
    .D(s_count),
    .Q(s_count_reg)
  );
  /* src = "../rtl/timer_unit/timer_unit_counter_presc.sv:60.4" */
  \$adff  #(
    .ARST_POLARITY(32'd0),
    .ARST_VALUE(1'h0),
    .CLK_POLARITY(32'd1),
    .WIDTH(32'd1)
  ) \$driver$target_reached_o  (
    .ARST(rst_ni),
    .CLK(clk_i),
    .D(\$auto$builder.cc:338:Biop$449 ),
    .Q(target_reached_o)
  );
  /* src = "../rtl/timer_unit/timer_unit_counter_presc.sv:46.16-46.42|../rtl/timer_unit/timer_unit_counter_presc.sv:45.14-46.42" */
  \$mux  #(
    .WIDTH(32'd32)
  ) \$procmux$625  (
    .A(s_count_reg),
    .B(\$auto$builder.cc:338:Biop$434 ),
    .S(enable_count_i),
    .Y(\$auto$slang_frontend.cc:694:finish$\s_count$435 )
  );
  /* full_case = 32'd1 */
  /* src = "../rtl/timer_unit/timer_unit_counter_presc.sv:42.12-42.38|../rtl/timer_unit/timer_unit_counter_presc.sv:41.9-47.12" */
  \$mux  #(
    .WIDTH(32'd32)
  ) \$procmux$635  (
    .A(\$auto$slang_frontend.cc:694:finish$\s_count$435 ),
    .B(counter_value_i),
    .S(write_counter_i),
    .Y(\$auto$slang_frontend.cc:694:finish$\s_count$436 )
  );
  /* full_case = 32'd1 */
  /* src = "../rtl/timer_unit/timer_unit_counter_presc.sv:38.8-38.20|../rtl/timer_unit/timer_unit_counter_presc.sv:37.6-48.9" */
  \$mux  #(
    .WIDTH(32'd32)
  ) \$procmux$642  (
    .A(\$auto$slang_frontend.cc:694:finish$\s_count$436 ),
    .B(32'd0),
    .S(\$auto$builder.cc:338:Biop$422 ),
    .Y(s_count)
  );
  assign counter_value_o = s_count_reg;
endmodule
