/* Generated by Yosys 0.51 (git sha1 c4b519022, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

/* top =  1  */
/* src = "../rtl/obi/obi_xbar.sv:8.8" */
module obi_xbar(clk_i, rst_ni, testmode_i, sbr_ports_req_i, sbr_ports_rsp_o, mgr_ports_req_o, mgr_ports_rsp_i, addr_map_i, en_default_idx_i, default_idx_i);
  /* src = "../rtl/obi/obi_xbar.sv:50.47" */
  input [1:0] addr_map_i;
  wire [1:0] addr_map_i;
  /* src = "../rtl/obi/obi_xbar.sv:40.16" */
  input clk_i;
  wire clk_i;
  /* src = "../rtl/obi/obi_xbar.sv:52.75" */
  input [1:0] default_idx_i;
  wire [1:0] default_idx_i;
  /* src = "../rtl/obi/obi_xbar.sv:51.47" */
  input [1:0] en_default_idx_i;
  wire [1:0] en_default_idx_i;
  /* src = "../rtl/obi/obi_xbar.sv:47.47" */
  output [1:0] mgr_ports_req_o;
  wire [1:0] mgr_ports_req_o;
  /* src = "../rtl/obi/obi_xbar.sv:48.47" */
  input [1:0] mgr_ports_rsp_i;
  wire [1:0] mgr_ports_rsp_i;
  /* src = "../rtl/obi/obi_xbar.sv:62.57" */
  wire [3:0] mgr_reqs;
  /* src = "../rtl/obi/obi_xbar.sv:63.57" */
  wire [3:0] mgr_rsps;
  /* src = "../rtl/obi/obi_xbar.sv:41.16" */
  input rst_ni;
  wire rst_ni;
  /* src = "../rtl/obi/obi_xbar.sv:55.68" */
  wire [1:0] sbr_port_select;
  /* src = "../rtl/obi/obi_xbar.sv:44.47" */
  input [1:0] sbr_ports_req_i;
  wire [1:0] sbr_ports_req_i;
  /* src = "../rtl/obi/obi_xbar.sv:45.47" */
  output [1:0] sbr_ports_rsp_o;
  wire [1:0] sbr_ports_rsp_o;
  /* src = "../rtl/obi/obi_xbar.sv:58.57" */
  wire [3:0] sbr_reqs;
  /* src = "../rtl/obi/obi_xbar.sv:59.57" */
  wire [3:0] sbr_rsps;
  /* src = "../rtl/obi/obi_xbar.sv:42.16" */
  input testmode_i;
  wire testmode_i;
endmodule
