/* Generated by Yosys 0.51 (git sha1 c4b519022, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

(* top =  1  *)
(* src = "../rtl/timer_unit/timer_unit.sv:37.8" *)
module timer_unit(clk_i, rst_ni, ref_clk_i, req_i, addr_i, wen_i, wdata_i, be_i, id_i, gnt_o, r_valid_o, r_opc_o, r_id_o, r_rdata_o, event_lo_i, event_hi_i, irq_lo_o, irq_hi_o, busy_o);
  wire \$auto$builder.cc:338:Biop$100 ;
  wire \$auto$builder.cc:338:Biop$104 ;
  wire \$auto$builder.cc:338:Biop$108 ;
  wire \$auto$builder.cc:338:Biop$112 ;
  wire \$auto$builder.cc:338:Biop$120 ;
  wire \$auto$builder.cc:338:Biop$124 ;
  wire \$auto$builder.cc:338:Biop$147 ;
  wire \$auto$builder.cc:338:Biop$158 ;
  wire \$auto$builder.cc:338:Biop$170 ;
  wire \$auto$builder.cc:338:Biop$183 ;
  wire \$auto$builder.cc:338:Biop$195 ;
  wire \$auto$builder.cc:338:Biop$207 ;
  wire \$auto$builder.cc:338:Biop$230 ;
  wire \$auto$builder.cc:338:Biop$237 ;
  wire \$auto$builder.cc:338:Biop$247 ;
  wire \$auto$builder.cc:338:Biop$249 ;
  wire \$auto$builder.cc:338:Biop$251 ;
  wire \$auto$builder.cc:338:Biop$259 ;
  wire \$auto$builder.cc:338:Biop$267 ;
  wire \$auto$builder.cc:338:Biop$28 ;
  wire \$auto$builder.cc:338:Biop$283 ;
  wire \$auto$builder.cc:338:Biop$285 ;
  wire \$auto$builder.cc:338:Biop$287 ;
  wire \$auto$builder.cc:338:Biop$295 ;
  wire \$auto$builder.cc:338:Biop$303 ;
  wire \$auto$builder.cc:338:Biop$319 ;
  wire \$auto$builder.cc:338:Biop$331 ;
  wire \$auto$builder.cc:338:Biop$353 ;
  wire \$auto$builder.cc:338:Biop$382 ;
  wire \$auto$builder.cc:338:Biop$384 ;
  wire \$auto$builder.cc:338:Biop$397 ;
  wire \$auto$builder.cc:338:Biop$407 ;
  wire \$auto$builder.cc:338:Biop$56 ;
  wire \$auto$builder.cc:338:Biop$60 ;
  wire \$auto$builder.cc:338:Biop$96 ;
  wire \$auto$builder.cc:364:Unop$26 ;
  wire \$auto$opt_dff.cc:194:make_patterns_logic$1198 ;
  wire \$auto$opt_dff.cc:194:make_patterns_logic$1200 ;
  wire \$auto$opt_dff.cc:194:make_patterns_logic$1209 ;
  wire \$auto$opt_dff.cc:194:make_patterns_logic$1211 ;
  wire \$auto$opt_dff.cc:219:make_patterns_logic$1189 ;
  wire \$auto$opt_dff.cc:219:make_patterns_logic$1192 ;
  wire \$auto$opt_dff.cc:219:make_patterns_logic$1195 ;
  wire \$auto$opt_dff.cc:219:make_patterns_logic$1202 ;
  wire \$auto$opt_dff.cc:219:make_patterns_logic$1206 ;
  wire \$auto$opt_dff.cc:219:make_patterns_logic$1213 ;
  wire \$auto$opt_share.cc:222:merge_operators$1217 ;
  wire \$auto$rtlil.cc:2874:Mux$1184 ;
  wire \$auto$rtlil.cc:2874:Mux$1187 ;
  wire \$auto$rtlil.cc:2874:Mux$1219 ;
  (* src = "../rtl/timer_unit/timer_unit.sv:285.14-305.21" *)
  wire [31:0] \$auto$slang_frontend.cc:694:finish$\r_rdata_o$150 ;
  (* src = "../rtl/timer_unit/timer_unit.sv:183.14-215.21" *)
  wire [31:0] \$auto$slang_frontend.cc:694:finish$\s_cfg_hi$38 ;
  (* src = "../rtl/timer_unit/timer_unit.sv:180.9-216.14" *)
  (* unused_bits = "2 4 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] \$auto$slang_frontend.cc:694:finish$\s_cfg_hi$48 ;
  (* src = "../rtl/timer_unit/timer_unit.sv:243.7-244.37" *)
  wire \$auto$slang_frontend.cc:694:finish$\s_cfg_hi[0]$127 ;
  (* src = "../rtl/timer_unit/timer_unit.sv:240.7-245.9" *)
  wire \$auto$slang_frontend.cc:694:finish$\s_cfg_hi[0]$128 ;
  (* src = "../rtl/timer_unit/timer_unit.sv:183.14-215.21" *)
  wire [31:0] \$auto$slang_frontend.cc:694:finish$\s_cfg_lo$37 ;
  (* src = "../rtl/timer_unit/timer_unit.sv:180.9-216.14" *)
  (* unused_bits = "2 4 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] \$auto$slang_frontend.cc:694:finish$\s_cfg_lo$47 ;
  (* src = "../rtl/timer_unit/timer_unit.sv:225.5-226.33" *)
  wire \$auto$slang_frontend.cc:694:finish$\s_cfg_lo[0]$75 ;
  (* src = "../rtl/timer_unit/timer_unit.sv:230.6-231.33" *)
  wire \$auto$slang_frontend.cc:694:finish$\s_cfg_lo[0]$88 ;
  (* src = "../rtl/timer_unit/timer_unit.sv:223.7-232.12" *)
  wire \$auto$slang_frontend.cc:694:finish$\s_cfg_lo[0]$89 ;
  (* src = "../rtl/timer_unit/timer_unit.sv:422.9-436.9" *)
  wire \$auto$slang_frontend.cc:694:finish$\s_enable_count_hi$308 ;
  (* src = "../rtl/timer_unit/timer_unit.sv:417.7-436.9" *)
  wire \$auto$slang_frontend.cc:694:finish$\s_enable_count_hi$310 ;
  (* src = "../rtl/timer_unit/timer_unit.sv:415.2-437.7" *)
  wire \$auto$slang_frontend.cc:694:finish$\s_enable_count_hi$312 ;
  (* src = "../rtl/timer_unit/timer_unit.sv:442.6-463.6" *)
  wire \$auto$slang_frontend.cc:694:finish$\s_enable_count_hi$369 ;
  (* src = "../rtl/timer_unit/timer_unit.sv:397.9-411.9" *)
  wire \$auto$slang_frontend.cc:694:finish$\s_enable_count_lo$272 ;
  (* src = "../rtl/timer_unit/timer_unit.sv:392.7-411.9" *)
  wire \$auto$slang_frontend.cc:694:finish$\s_enable_count_lo$274 ;
  (* src = "../rtl/timer_unit/timer_unit.sv:390.2-412.7" *)
  wire \$auto$slang_frontend.cc:694:finish$\s_enable_count_lo$276 ;
  (* src = "../rtl/timer_unit/timer_unit.sv:427.4-436.9" *)
  wire \$auto$slang_frontend.cc:694:finish$\s_enable_count_prescaler_hi$307 ;
  (* src = "../rtl/timer_unit/timer_unit.sv:422.9-436.9" *)
  wire \$auto$slang_frontend.cc:694:finish$\s_enable_count_prescaler_hi$309 ;
  (* src = "../rtl/timer_unit/timer_unit.sv:417.7-436.9" *)
  wire \$auto$slang_frontend.cc:694:finish$\s_enable_count_prescaler_hi$311 ;
  (* src = "../rtl/timer_unit/timer_unit.sv:402.4-411.9" *)
  wire \$auto$slang_frontend.cc:694:finish$\s_enable_count_prescaler_lo$271 ;
  (* src = "../rtl/timer_unit/timer_unit.sv:397.9-411.9" *)
  wire \$auto$slang_frontend.cc:694:finish$\s_enable_count_prescaler_lo$273 ;
  (* src = "../rtl/timer_unit/timer_unit.sv:392.7-411.9" *)
  wire \$auto$slang_frontend.cc:694:finish$\s_enable_count_prescaler_lo$275 ;
  (* src = "../rtl/timer_unit/timer_unit.sv:390.2-412.7" *)
  wire \$auto$slang_frontend.cc:694:finish$\s_enable_count_prescaler_lo$277 ;
  (* src = "../rtl/timer_unit/timer_unit.sv:447.11-463.6" *)
  wire \$auto$slang_frontend.cc:694:finish$\s_enable_count_prescaler_lo$367 ;
  (* src = "../rtl/timer_unit/timer_unit.sv:442.6-463.6" *)
  wire \$auto$slang_frontend.cc:694:finish$\s_enable_count_prescaler_lo$370 ;
  (* src = "../rtl/timer_unit/timer_unit.sv:353.7-366.12" *)
  wire \$auto$slang_frontend.cc:694:finish$\s_reset_count_hi$224 ;
  (* src = "../rtl/timer_unit/timer_unit.sv:330.7-343.12" *)
  wire \$auto$slang_frontend.cc:694:finish$\s_reset_count_lo$187 ;
  (* src = "../rtl/timer_unit/timer_unit.sv:183.14-215.21" *)
  wire \$auto$slang_frontend.cc:694:finish$\s_reset_timer_hi$36 ;
  (* src = "../rtl/timer_unit/timer_unit.sv:183.14-215.21" *)
  wire \$auto$slang_frontend.cc:694:finish$\s_reset_timer_lo$35 ;
  (* src = "../rtl/timer_unit/timer_unit.sv:183.14-215.21" *)
  wire \$auto$slang_frontend.cc:694:finish$\s_start_timer_hi$34 ;
  (* src = "../rtl/timer_unit/timer_unit.sv:183.14-215.21" *)
  wire \$auto$slang_frontend.cc:694:finish$\s_start_timer_lo$33 ;
  (* src = "../rtl/timer_unit/timer_unit.sv:183.14-215.21" *)
  wire \$auto$slang_frontend.cc:694:finish$\s_write_counter_hi$32 ;
  (* src = "../rtl/timer_unit/timer_unit.sv:183.14-215.21" *)
  wire \$auto$slang_frontend.cc:694:finish$\s_write_counter_lo$31 ;
  wire \$procmux$645_CMP ;
  wire \$procmux$646_CMP ;
  wire \$procmux$647_CMP ;
  wire \$procmux$648_CMP ;
  wire \$procmux$649_CMP ;
  wire \$procmux$650_CMP ;
  wire \$procmux$735_CMP ;
  wire \$procmux$744_CMP ;
  wire \$procmux$756_CMP ;
  wire \$procmux$769_CMP ;
  (* src = "../rtl/timer_unit/timer_unit.sv:48.39" *)
  input [31:0] addr_i;
  wire [31:0] addr_i;
  (* src = "../rtl/timer_unit/timer_unit.sv:51.39" *)
  input [3:0] be_i;
  wire [3:0] be_i;
  (* src = "../rtl/timer_unit/timer_unit.sv:66.39" *)
  output busy_o;
  wire busy_o;
  (* src = "../rtl/timer_unit/timer_unit.sv:42.39" *)
  input clk_i;
  wire clk_i;
  (* src = "../rtl/timer_unit/timer_unit.sv:61.39" *)
  input event_hi_i;
  wire event_hi_i;
  (* src = "../rtl/timer_unit/timer_unit.sv:60.39" *)
  input event_lo_i;
  wire event_lo_i;
  (* src = "../rtl/timer_unit/timer_unit.sv:53.39" *)
  output gnt_o;
  wire gnt_o;
  (* src = "../rtl/timer_unit/timer_unit.sv:52.39" *)
  input [4:0] id_i;
  wire [4:0] id_i;
  (* src = "../rtl/timer_unit/timer_unit.sv:64.39" *)
  output irq_hi_o;
  wire irq_hi_o;
  (* src = "../rtl/timer_unit/timer_unit.sv:63.39" *)
  output irq_lo_o;
  wire irq_lo_o;
  (* src = "../rtl/timer_unit/timer_unit.sv:57.39" *)
  output [4:0] r_id_o;
  reg [4:0] r_id_o;
  (* src = "../rtl/timer_unit/timer_unit.sv:56.39" *)
  output r_opc_o;
  wire r_opc_o;
  (* src = "../rtl/timer_unit/timer_unit.sv:58.39" *)
  output [31:0] r_rdata_o;
  wire [31:0] r_rdata_o;
  (* src = "../rtl/timer_unit/timer_unit.sv:55.39" *)
  output r_valid_o;
  reg r_valid_o;
  (* src = "../rtl/timer_unit/timer_unit.sv:45.39" *)
  input ref_clk_i;
  wire ref_clk_i;
  (* src = "../rtl/timer_unit/timer_unit.sv:47.39" *)
  input req_i;
  wire req_i;
  (* src = "../rtl/timer_unit/timer_unit.sv:43.39" *)
  input rst_ni;
  wire rst_ni;
  (* src = "../rtl/timer_unit/timer_unit.sv:70.25" *)
  (* unused_bits = "6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  reg [31:0] s_addr;
  (* src = "../rtl/timer_unit/timer_unit.sv:80.25" *)
  (* unused_bits = "2 4 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] s_cfg_hi;
  (* src = "../rtl/timer_unit/timer_unit.sv:80.35" *)
  wire [31:0] s_cfg_hi_reg;
  (* src = "../rtl/timer_unit/timer_unit.sv:79.25" *)
  (* unused_bits = "2 4 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] s_cfg_lo;
  (* src = "../rtl/timer_unit/timer_unit.sv:79.35" *)
  wire [31:0] s_cfg_lo_reg;
  (* src = "../rtl/timer_unit/timer_unit.sv:86.37" *)
  wire s_enable_count_hi;
  (* src = "../rtl/timer_unit/timer_unit.sv:86.19" *)
  wire s_enable_count_lo;
  (* src = "../rtl/timer_unit/timer_unit.sv:86.83" *)
  wire s_enable_count_prescaler_hi;
  (* src = "../rtl/timer_unit/timer_unit.sv:86.55" *)
  wire s_enable_count_prescaler_lo;
  (* src = "../rtl/timer_unit/timer_unit.sv:75.19" *)
  reg s_ref_clk0;
  (* src = "../rtl/timer_unit/timer_unit.sv:75.31" *)
  reg s_ref_clk1;
  (* src = "../rtl/timer_unit/timer_unit.sv:75.43" *)
  reg s_ref_clk2;
  (* src = "../rtl/timer_unit/timer_unit.sv:75.55" *)
  reg s_ref_clk3;
  (* src = "../rtl/timer_unit/timer_unit.sv:75.67" *)
  wire s_ref_clk_edge;
  (* src = "../rtl/timer_unit/timer_unit.sv:75.83" *)
  wire s_ref_clk_edge_del;
  (* src = "../rtl/timer_unit/timer_unit.sv:87.36" *)
  wire s_reset_count_hi;
  (* src = "../rtl/timer_unit/timer_unit.sv:87.19" *)
  wire s_reset_count_lo;
  (* src = "../rtl/timer_unit/timer_unit.sv:87.80" *)
  wire s_reset_count_prescaler_hi;
  (* src = "../rtl/timer_unit/timer_unit.sv:87.53" *)
  wire s_reset_count_prescaler_lo;
  (* src = "../rtl/timer_unit/timer_unit.sv:73.70" *)
  wire s_reset_timer_hi;
  (* src = "../rtl/timer_unit/timer_unit.sv:73.53" *)
  wire s_reset_timer_lo;
  (* src = "../rtl/timer_unit/timer_unit.sv:73.36" *)
  wire s_start_timer_hi;
  (* src = "../rtl/timer_unit/timer_unit.sv:73.19" *)
  wire s_start_timer_lo;
  (* src = "../rtl/timer_unit/timer_unit.sv:88.39" *)
  wire s_target_reached_hi;
  (* src = "../rtl/timer_unit/timer_unit.sv:88.19" *)
  wire s_target_reached_lo;
  (* src = "../rtl/timer_unit/timer_unit.sv:88.90" *)
  wire s_target_reached_prescaler_hi;
  (* src = "../rtl/timer_unit/timer_unit.sv:88.59" *)
  wire s_target_reached_prescaler_lo;
  (* src = "../rtl/timer_unit/timer_unit.sv:84.41" *)
  reg [31:0] s_timer_cmp_hi_reg;
  (* src = "../rtl/timer_unit/timer_unit.sv:83.41" *)
  reg [31:0] s_timer_cmp_lo_reg;
  (* src = "../rtl/timer_unit/timer_unit.sv:82.25" *)
  wire [31:0] s_timer_val_hi;
  (* src = "../rtl/timer_unit/timer_unit.sv:81.25" *)
  wire [31:0] s_timer_val_lo;
  (* src = "../rtl/timer_unit/timer_unit.sv:69.25" *)
  reg s_wen;
  (* src = "../rtl/timer_unit/timer_unit.sv:72.39" *)
  wire s_write_counter_hi;
  (* src = "../rtl/timer_unit/timer_unit.sv:72.19" *)
  wire s_write_counter_lo;
  (* src = "../rtl/timer_unit/timer_unit.sv:50.39" *)
  input [31:0] wdata_i;
  wire [31:0] wdata_i;
  (* src = "../rtl/timer_unit/timer_unit.sv:49.39" *)
  input wen_i;
  wire wen_i;
  assign \$auto$builder.cc:338:Biop$104  = ~ s_cfg_hi_reg[31];
  assign \$auto$builder.cc:338:Biop$108  = \$auto$builder.cc:338:Biop$104  && s_cfg_hi[5];
  assign \$auto$builder.cc:338:Biop$112  = \$auto$builder.cc:338:Biop$108  && s_target_reached_hi;
  assign \$auto$builder.cc:338:Biop$120  = s_cfg_lo[5] && s_target_reached_lo;
  assign \$auto$builder.cc:338:Biop$124  = \$auto$builder.cc:338:Biop$120  && s_target_reached_hi;
  assign \$auto$builder.cc:338:Biop$147  = r_valid_o && s_wen;
  assign \$auto$builder.cc:338:Biop$158  = s_cfg_lo_reg[1] | s_reset_timer_lo;
  assign \$auto$builder.cc:338:Biop$170  = s_cfg_lo_reg[4] && s_target_reached_lo;
  assign \$auto$builder.cc:338:Biop$183  = \$auto$builder.cc:338:Biop$170  && s_target_reached_hi;
  assign \$auto$builder.cc:338:Biop$195  = s_cfg_hi_reg[1] | s_reset_timer_hi;
  assign \$auto$builder.cc:338:Biop$207  = s_cfg_hi_reg[4] && s_target_reached_hi;
  assign \$auto$builder.cc:338:Biop$230  = s_cfg_lo_reg[6] && s_target_reached_prescaler_lo;
  assign \$auto$builder.cc:338:Biop$237  = s_cfg_hi_reg[6] && s_target_reached_prescaler_hi;
  assign \$auto$builder.cc:338:Biop$247  = ~ s_cfg_lo_reg[6];
  assign \$auto$builder.cc:338:Biop$249  = ~ s_cfg_lo_reg[7];
  assign \$auto$builder.cc:338:Biop$251  = \$auto$builder.cc:338:Biop$247  && \$auto$builder.cc:338:Biop$249 ;
  assign \$auto$builder.cc:338:Biop$259  = \$auto$builder.cc:338:Biop$247  && s_cfg_lo_reg[7];
  assign \$auto$builder.cc:338:Biop$267  = s_cfg_lo_reg[6] && s_cfg_lo_reg[7];
  assign \$auto$builder.cc:338:Biop$28  = req_i && \$auto$builder.cc:364:Unop$26 ;
  assign \$auto$builder.cc:338:Biop$283  = ~ s_cfg_hi_reg[6];
  assign \$auto$builder.cc:338:Biop$285  = ~ s_cfg_hi_reg[7];
  assign \$auto$builder.cc:338:Biop$287  = \$auto$builder.cc:338:Biop$283  && \$auto$builder.cc:338:Biop$285 ;
  assign \$auto$builder.cc:338:Biop$295  = \$auto$builder.cc:338:Biop$283  && s_cfg_hi_reg[7];
  assign \$auto$builder.cc:338:Biop$303  = s_cfg_hi_reg[6] && s_cfg_hi_reg[7];
  assign \$auto$builder.cc:338:Biop$319  = s_cfg_lo_reg[0] && s_cfg_lo_reg[31];
  assign \$auto$builder.cc:338:Biop$331  = s_timer_val_lo == 32'd4294967295;
  assign \$auto$opt_share.cc:222:merge_operators$1217  = \$auto$rtlil.cc:2874:Mux$1219  && \$auto$builder.cc:338:Biop$331 ;
  assign \$auto$builder.cc:338:Biop$353  = s_target_reached_prescaler_lo && s_ref_clk_edge_del;
  assign \$auto$builder.cc:338:Biop$382  = s_target_reached_hi & s_cfg_hi_reg[2];
  assign \$auto$builder.cc:338:Biop$384  = s_target_reached_lo & s_target_reached_hi;
  assign irq_lo_o = \$auto$rtlil.cc:2874:Mux$1184  & s_cfg_lo_reg[2];
  assign \$auto$builder.cc:338:Biop$397  = ~ s_ref_clk2;
  assign s_ref_clk_edge = s_ref_clk1 & \$auto$builder.cc:338:Biop$397 ;
  assign \$auto$builder.cc:338:Biop$407  = ~ s_ref_clk3;
  assign s_ref_clk_edge_del = s_ref_clk2 & \$auto$builder.cc:338:Biop$407 ;
  assign busy_o = s_cfg_hi_reg[0] | s_cfg_lo_reg[0];
  assign \$auto$builder.cc:338:Biop$56  = event_lo_i && s_cfg_lo[3];
  assign \$auto$builder.cc:338:Biop$60  = \$auto$builder.cc:338:Biop$56  | s_start_timer_lo;
  assign \$auto$builder.cc:338:Biop$96  = event_hi_i && s_cfg_hi[3];
  assign \$auto$builder.cc:338:Biop$100  = \$auto$builder.cc:338:Biop$96  | s_start_timer_hi;
  assign \$auto$builder.cc:364:Unop$26  = ~ wen_i;
  (* src = "../rtl/timer_unit/timer_unit.sv:259.4" *)
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) s_timer_cmp_lo_reg <= 32'd0;
    else if (\$auto$opt_dff.cc:219:make_patterns_logic$1189 ) s_timer_cmp_lo_reg <= wdata_i;
  (* src = "../rtl/timer_unit/timer_unit.sv:259.4" *)
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) s_timer_cmp_hi_reg <= 32'd0;
    else if (\$auto$opt_dff.cc:219:make_patterns_logic$1192 ) s_timer_cmp_hi_reg <= wdata_i;
  reg [27:0] \$auto$ff.cc:266:slice$1194 ;
  (* src = "../rtl/timer_unit/timer_unit.sv:259.4" *)
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) \$auto$ff.cc:266:slice$1194  <= 28'h0000000;
    else if (\$auto$opt_dff.cc:219:make_patterns_logic$1195 ) \$auto$ff.cc:266:slice$1194  <= { wdata_i[31:6], wdata_i[4], wdata_i[2] };
  assign { s_cfg_lo_reg[31:6], s_cfg_lo_reg[4], s_cfg_lo_reg[2] } = \$auto$ff.cc:266:slice$1194 ;
  reg \$auto$ff.cc:266:slice$1197 ;
  (* src = "../rtl/timer_unit/timer_unit.sv:259.4" *)
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) \$auto$ff.cc:266:slice$1197  <= 1'h0;
    else if (\$auto$opt_dff.cc:219:make_patterns_logic$1202 ) \$auto$ff.cc:266:slice$1197  <= s_cfg_lo[1];
  assign s_cfg_lo_reg[1] = \$auto$ff.cc:266:slice$1197 ;
  reg [2:0] \$auto$ff.cc:266:slice$1204 ;
  (* src = "../rtl/timer_unit/timer_unit.sv:259.4" *)
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) \$auto$ff.cc:266:slice$1204  <= 3'h0;
    else \$auto$ff.cc:266:slice$1204  <= { s_cfg_lo[5], s_cfg_lo[3], s_cfg_lo[0] };
  assign { s_cfg_lo_reg[5], s_cfg_lo_reg[3], s_cfg_lo_reg[0] } = \$auto$ff.cc:266:slice$1204 ;
  reg [27:0] \$auto$ff.cc:266:slice$1205 ;
  (* src = "../rtl/timer_unit/timer_unit.sv:259.4" *)
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) \$auto$ff.cc:266:slice$1205  <= 28'h0000000;
    else if (\$auto$opt_dff.cc:219:make_patterns_logic$1206 ) \$auto$ff.cc:266:slice$1205  <= { wdata_i[31:6], wdata_i[4], wdata_i[2] };
  assign { s_cfg_hi_reg[31:6], s_cfg_hi_reg[4], s_cfg_hi_reg[2] } = \$auto$ff.cc:266:slice$1205 ;
  reg \$auto$ff.cc:266:slice$1208 ;
  (* src = "../rtl/timer_unit/timer_unit.sv:259.4" *)
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) \$auto$ff.cc:266:slice$1208  <= 1'h0;
    else if (\$auto$opt_dff.cc:219:make_patterns_logic$1213 ) \$auto$ff.cc:266:slice$1208  <= s_cfg_hi[1];
  assign s_cfg_hi_reg[1] = \$auto$ff.cc:266:slice$1208 ;
  reg [2:0] \$auto$ff.cc:266:slice$1215 ;
  (* src = "../rtl/timer_unit/timer_unit.sv:259.4" *)
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) \$auto$ff.cc:266:slice$1215  <= 3'h0;
    else \$auto$ff.cc:266:slice$1215  <= { s_cfg_hi[5], s_cfg_hi[3], s_cfg_hi[0] };
  assign { s_cfg_hi_reg[5], s_cfg_hi_reg[3], s_cfg_hi_reg[0] } = \$auto$ff.cc:266:slice$1215 ;
  (* src = "../rtl/timer_unit/timer_unit.sv:98.4" *)
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) r_valid_o <= 1'h0;
    else r_valid_o <= req_i;
  assign \$auto$opt_dff.cc:194:make_patterns_logic$1198  = | { \$auto$builder.cc:338:Biop$28 , s_reset_count_lo };
  assign \$auto$opt_dff.cc:194:make_patterns_logic$1200  = { \$procmux$769_CMP , \$auto$builder.cc:338:Biop$28 , s_reset_count_lo } != 3'h2;
  assign \$auto$opt_dff.cc:194:make_patterns_logic$1209  = | { \$auto$builder.cc:338:Biop$28 , s_reset_count_hi };
  assign \$auto$opt_dff.cc:194:make_patterns_logic$1211  = { \$procmux$756_CMP , \$auto$builder.cc:338:Biop$28 , s_reset_count_hi } != 3'h2;
  assign \$auto$opt_dff.cc:219:make_patterns_logic$1189  = & { \$procmux$744_CMP , \$auto$builder.cc:338:Biop$28  };
  assign \$auto$opt_dff.cc:219:make_patterns_logic$1192  = & { \$procmux$735_CMP , \$auto$builder.cc:338:Biop$28  };
  assign \$auto$opt_dff.cc:219:make_patterns_logic$1195  = & { \$procmux$769_CMP , \$auto$builder.cc:338:Biop$28  };
  assign \$auto$opt_dff.cc:219:make_patterns_logic$1202  = & { \$auto$opt_dff.cc:194:make_patterns_logic$1198 , \$auto$opt_dff.cc:194:make_patterns_logic$1200  };
  assign \$auto$opt_dff.cc:219:make_patterns_logic$1206  = & { \$procmux$756_CMP , \$auto$builder.cc:338:Biop$28  };
  assign \$auto$opt_dff.cc:219:make_patterns_logic$1213  = & { \$auto$opt_dff.cc:194:make_patterns_logic$1211 , \$auto$opt_dff.cc:194:make_patterns_logic$1209  };
  assign \$auto$rtlil.cc:2874:Mux$1184  = s_cfg_lo_reg[31] ? \$auto$builder.cc:338:Biop$384  : s_target_reached_lo;
  assign \$auto$rtlil.cc:2874:Mux$1187  = \$auto$builder.cc:338:Biop$267  ? \$auto$builder.cc:338:Biop$353  : s_target_reached_prescaler_lo;
  assign \$auto$rtlil.cc:2874:Mux$1219  = \$auto$builder.cc:338:Biop$259  ? s_ref_clk_edge_del : \$auto$rtlil.cc:2874:Mux$1187 ;
  (* src = "../rtl/timer_unit/timer_unit.sv:142.4" *)
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) r_id_o <= 5'h00;
    else r_id_o <= id_i;
  (* src = "../rtl/timer_unit/timer_unit.sv:142.4" *)
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) s_addr <= 32'd0;
    else s_addr <= addr_i;
  (* src = "../rtl/timer_unit/timer_unit.sv:488.4" *)
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) s_ref_clk0 <= 1'h0;
    else s_ref_clk0 <= ref_clk_i;
  (* src = "../rtl/timer_unit/timer_unit.sv:488.4" *)
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) s_ref_clk1 <= 1'h0;
    else s_ref_clk1 <= s_ref_clk0;
  (* src = "../rtl/timer_unit/timer_unit.sv:488.4" *)
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) s_ref_clk2 <= 1'h0;
    else s_ref_clk2 <= s_ref_clk1;
  (* src = "../rtl/timer_unit/timer_unit.sv:488.4" *)
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) s_ref_clk3 <= 1'h0;
    else s_ref_clk3 <= s_ref_clk2;
  (* src = "../rtl/timer_unit/timer_unit.sv:142.4" *)
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) s_wen <= 1'h0;
    else s_wen <= wen_i;
  assign \$auto$slang_frontend.cc:694:finish$\s_enable_count_hi$310  = \$auto$slang_frontend.cc:694:finish$\s_enable_count_hi$308  | (* full_case = 32'd1 *) (* src = "../rtl/timer_unit/timer_unit.sv:419.5-419.30|../rtl/timer_unit/timer_unit.sv:417.7-436.9" *) \$auto$builder.cc:338:Biop$287 ;
  assign \$auto$slang_frontend.cc:694:finish$\s_enable_count_prescaler_hi$311  = \$auto$builder.cc:338:Biop$287  ? (* full_case = 32'd1 *) (* src = "../rtl/timer_unit/timer_unit.sv:419.5-419.30|../rtl/timer_unit/timer_unit.sv:417.7-436.9" *) 1'h0 : \$auto$slang_frontend.cc:694:finish$\s_enable_count_prescaler_hi$309 ;
  assign s_enable_count_prescaler_hi = s_cfg_hi_reg[0] & (* src = "../rtl/timer_unit/timer_unit.sv:417.7-436.9|../rtl/timer_unit/timer_unit.sv:415.2-437.7" *) \$auto$slang_frontend.cc:694:finish$\s_enable_count_prescaler_hi$311 ;
  assign \$auto$slang_frontend.cc:694:finish$\s_enable_count_hi$312  = s_cfg_hi_reg[0] & (* src = "../rtl/timer_unit/timer_unit.sv:417.7-436.9|../rtl/timer_unit/timer_unit.sv:415.2-437.7" *) \$auto$slang_frontend.cc:694:finish$\s_enable_count_hi$310 ;
  assign \$auto$slang_frontend.cc:694:finish$\s_enable_count_prescaler_lo$273  = \$auto$builder.cc:338:Biop$259  ? (* full_case = 32'd1 *) (* src = "../rtl/timer_unit/timer_unit.sv:399.7-399.42|../rtl/timer_unit/timer_unit.sv:397.9-411.9" *) 1'h0 : \$auto$slang_frontend.cc:694:finish$\s_enable_count_prescaler_lo$271 ;
  assign \$auto$slang_frontend.cc:694:finish$\s_enable_count_lo$274  = \$auto$slang_frontend.cc:694:finish$\s_enable_count_lo$272  | (* full_case = 32'd1 *) (* src = "../rtl/timer_unit/timer_unit.sv:394.5-394.30|../rtl/timer_unit/timer_unit.sv:392.7-411.9" *) \$auto$builder.cc:338:Biop$251 ;
  assign \$auto$slang_frontend.cc:694:finish$\s_enable_count_prescaler_lo$275  = \$auto$builder.cc:338:Biop$251  ? (* full_case = 32'd1 *) (* src = "../rtl/timer_unit/timer_unit.sv:394.5-394.30|../rtl/timer_unit/timer_unit.sv:392.7-411.9" *) 1'h0 : \$auto$slang_frontend.cc:694:finish$\s_enable_count_prescaler_lo$273 ;
  assign \$auto$slang_frontend.cc:694:finish$\s_enable_count_prescaler_lo$277  = s_cfg_lo_reg[0] & (* src = "../rtl/timer_unit/timer_unit.sv:392.7-411.9|../rtl/timer_unit/timer_unit.sv:390.2-412.7" *) \$auto$slang_frontend.cc:694:finish$\s_enable_count_prescaler_lo$275 ;
  assign \$auto$slang_frontend.cc:694:finish$\s_enable_count_lo$276  = s_cfg_lo_reg[0] & (* src = "../rtl/timer_unit/timer_unit.sv:392.7-411.9|../rtl/timer_unit/timer_unit.sv:390.2-412.7" *) \$auto$slang_frontend.cc:694:finish$\s_enable_count_lo$274 ;
  assign s_reset_count_prescaler_hi = \$auto$builder.cc:338:Biop$195  | (* src = "../rtl/timer_unit/timer_unit.sv:376.7-376.41|../rtl/timer_unit/timer_unit.sv:374.2-377.7" *) \$auto$builder.cc:338:Biop$237 ;
  assign s_reset_count_prescaler_lo = \$auto$builder.cc:338:Biop$158  | (* src = "../rtl/timer_unit/timer_unit.sv:371.7-371.41|../rtl/timer_unit/timer_unit.sv:369.2-372.7" *) \$auto$builder.cc:338:Biop$230 ;
  assign \$auto$slang_frontend.cc:694:finish$\s_reset_count_hi$224  = s_cfg_lo_reg[31] ? (* full_case = 32'd1 *) (* src = "../rtl/timer_unit/timer_unit.sv:355.5-358.10|../rtl/timer_unit/timer_unit.sv:353.7-366.12" *) \$auto$builder.cc:338:Biop$183  : \$auto$builder.cc:338:Biop$207 ;
  assign s_reset_count_hi = \$auto$slang_frontend.cc:694:finish$\s_reset_count_hi$224  | (* full_case = 32'd1 *) (* src = "../rtl/timer_unit/timer_unit.sv:347.4-350.7|../rtl/timer_unit/timer_unit.sv:346.2-367.14" *) \$auto$builder.cc:338:Biop$195 ;
  assign \$auto$slang_frontend.cc:694:finish$\s_reset_count_lo$187  = s_cfg_lo_reg[31] ? (* full_case = 32'd1 *) (* src = "../rtl/timer_unit/timer_unit.sv:332.5-335.10|../rtl/timer_unit/timer_unit.sv:330.7-343.12" *) \$auto$builder.cc:338:Biop$183  : \$auto$builder.cc:338:Biop$170 ;
  assign s_reset_count_lo = \$auto$slang_frontend.cc:694:finish$\s_reset_count_lo$187  | (* full_case = 32'd1 *) (* src = "../rtl/timer_unit/timer_unit.sv:324.4-327.7|../rtl/timer_unit/timer_unit.sv:323.2-344.7" *) \$auto$builder.cc:338:Biop$158 ;
  function [31:0] \$procmux$644 ;
    input [31:0] a;
    input [191:0] b;
    input [5:0] s;
    (* src = "../rtl/timer_unit/timer_unit.sv:303.18-303.49|../rtl/timer_unit/timer_unit.sv:285.14-305.21" *)
    (* parallel_case *)
    casez (s)
      6'b?????1:
        \$procmux$644  = b[31:0];
      6'b????1?:
        \$procmux$644  = b[63:32];
      6'b???1??:
        \$procmux$644  = b[95:64];
      6'b??1???:
        \$procmux$644  = b[127:96];
      6'b?1????:
        \$procmux$644  = b[159:128];
      6'b1?????:
        \$procmux$644  = b[191:160];
      default:
        \$procmux$644  = a;
    endcase
  endfunction
  assign \$auto$slang_frontend.cc:694:finish$\r_rdata_o$150  = \$procmux$644 (32'd0, { s_cfg_lo_reg, s_cfg_hi_reg, s_timer_val_lo, s_timer_val_hi, s_timer_cmp_lo_reg, s_timer_cmp_hi_reg }, { \$procmux$650_CMP , \$procmux$649_CMP , \$procmux$648_CMP , \$procmux$647_CMP , \$procmux$646_CMP , \$procmux$645_CMP  });
  assign \$procmux$645_CMP  = s_addr[5:0] == (* src = "../rtl/timer_unit/timer_unit.sv:303.18-303.49|../rtl/timer_unit/timer_unit.sv:285.14-305.21" *) 5'h14;
  assign \$procmux$646_CMP  = s_addr[5:0] == (* src = "../rtl/timer_unit/timer_unit.sv:300.18-300.49|../rtl/timer_unit/timer_unit.sv:285.14-305.21" *) 5'h10;
  assign \$procmux$647_CMP  = s_addr[5:0] == (* src = "../rtl/timer_unit/timer_unit.sv:297.18-297.45|../rtl/timer_unit/timer_unit.sv:285.14-305.21" *) 4'hc;
  assign \$procmux$648_CMP  = s_addr[5:0] == (* src = "../rtl/timer_unit/timer_unit.sv:294.18-294.45|../rtl/timer_unit/timer_unit.sv:285.14-305.21" *) 4'h8;
  assign \$procmux$649_CMP  = s_addr[5:0] == (* src = "../rtl/timer_unit/timer_unit.sv:291.18-291.43|../rtl/timer_unit/timer_unit.sv:285.14-305.21" *) 3'h4;
  assign \$procmux$650_CMP  = ! (* src = "../rtl/timer_unit/timer_unit.sv:288.18-288.43|../rtl/timer_unit/timer_unit.sv:285.14-305.21" *) s_addr[5:0];
  assign r_rdata_o = \$auto$builder.cc:338:Biop$147  ? (* src = "../rtl/timer_unit/timer_unit.sv:285.14-305.21|../rtl/timer_unit/timer_unit.sv:282.9-307.14" *) \$auto$slang_frontend.cc:694:finish$\r_rdata_o$150  : 32'd0;
  assign irq_hi_o = s_cfg_lo_reg[31] ? (* full_case = 32'd1 *) (* src = "../rtl/timer_unit/timer_unit.sv:474.4-477.7|../rtl/timer_unit/timer_unit.sv:473.2-481.7" *) 1'h0 : \$auto$builder.cc:338:Biop$382 ;
  assign s_cfg_hi[1] = s_reset_count_hi ? (* src = "../rtl/timer_unit/timer_unit.sv:254.4-254.32|../rtl/timer_unit/timer_unit.sv:253.2-254.32" *) 1'h0 : \$auto$slang_frontend.cc:694:finish$\s_cfg_hi$48 [1];
  assign s_cfg_lo[1] = s_reset_count_lo ? (* src = "../rtl/timer_unit/timer_unit.sv:250.4-250.32|../rtl/timer_unit/timer_unit.sv:249.2-250.32" *) 1'h0 : \$auto$slang_frontend.cc:694:finish$\s_cfg_lo$47 [1];
  assign \$auto$slang_frontend.cc:694:finish$\s_cfg_hi[0]$127  = \$auto$builder.cc:338:Biop$124  ? (* src = "../rtl/timer_unit/timer_unit.sv:244.11-244.37|../rtl/timer_unit/timer_unit.sv:243.7-244.37" *) 1'h0 : \$auto$slang_frontend.cc:694:finish$\s_cfg_hi$48 [0];
  assign \$auto$slang_frontend.cc:694:finish$\s_cfg_hi[0]$128  = \$auto$builder.cc:338:Biop$112  ? (* full_case = 32'd1 *) (* src = "../rtl/timer_unit/timer_unit.sv:241.9-241.35|../rtl/timer_unit/timer_unit.sv:240.7-245.9" *) 1'h0 : \$auto$slang_frontend.cc:694:finish$\s_cfg_hi[0]$127 ;
  assign s_cfg_hi[0] = \$auto$slang_frontend.cc:694:finish$\s_cfg_hi[0]$128  | (* full_case = 32'd1 *) (* src = "../rtl/timer_unit/timer_unit.sv:237.4-237.30|../rtl/timer_unit/timer_unit.sv:236.2-246.7" *) \$auto$builder.cc:338:Biop$100 ;
  assign \$auto$slang_frontend.cc:694:finish$\s_cfg_lo[0]$88  = \$auto$builder.cc:338:Biop$124  ? (* src = "../rtl/timer_unit/timer_unit.sv:231.7-231.33|../rtl/timer_unit/timer_unit.sv:230.6-231.33" *) 1'h0 : \$auto$slang_frontend.cc:694:finish$\s_cfg_lo$47 [0];
  assign \$auto$slang_frontend.cc:694:finish$\s_cfg_lo[0]$89  = s_cfg_lo_reg[31] ? (* full_case = 32'd1 *) (* src = "../rtl/timer_unit/timer_unit.sv:225.5-226.33|../rtl/timer_unit/timer_unit.sv:223.7-232.12" *) \$auto$slang_frontend.cc:694:finish$\s_cfg_lo[0]$88  : \$auto$slang_frontend.cc:694:finish$\s_cfg_lo[0]$75 ;
  assign \$auto$slang_frontend.cc:694:finish$\s_cfg_lo[0]$75  = \$auto$builder.cc:338:Biop$120  ? (* src = "../rtl/timer_unit/timer_unit.sv:226.7-226.33|../rtl/timer_unit/timer_unit.sv:225.5-226.33" *) 1'h0 : \$auto$slang_frontend.cc:694:finish$\s_cfg_lo$47 [0];
  assign s_cfg_lo[0] = \$auto$slang_frontend.cc:694:finish$\s_cfg_lo[0]$89  | (* full_case = 32'd1 *) (* src = "../rtl/timer_unit/timer_unit.sv:220.4-220.30|../rtl/timer_unit/timer_unit.sv:219.2-233.7" *) \$auto$builder.cc:338:Biop$60 ;
  assign \$procmux$735_CMP  = addr_i[5:0] == (* src = "../rtl/timer_unit/timer_unit.sv:201.18-201.47|../rtl/timer_unit/timer_unit.sv:183.14-215.21" *) 5'h14;
  assign \$procmux$744_CMP  = addr_i[5:0] == (* src = "../rtl/timer_unit/timer_unit.sv:198.18-198.47|../rtl/timer_unit/timer_unit.sv:183.14-215.21" *) 5'h10;
  assign \$auto$slang_frontend.cc:694:finish$\s_cfg_hi$38  = \$procmux$756_CMP  ? (* src = "../rtl/timer_unit/timer_unit.sv:189.4-189.33|../rtl/timer_unit/timer_unit.sv:183.14-215.21" *) wdata_i : { s_cfg_hi_reg[31:2], 1'hx, s_cfg_hi_reg[0] };
  assign \$procmux$756_CMP  = addr_i[5:0] == (* src = "../rtl/timer_unit/timer_unit.sv:189.4-189.33|../rtl/timer_unit/timer_unit.sv:183.14-215.21" *) 3'h4;
  assign \$auto$slang_frontend.cc:694:finish$\s_cfg_lo$37  = \$procmux$769_CMP  ? (* src = "../rtl/timer_unit/timer_unit.sv:186.4-186.33|../rtl/timer_unit/timer_unit.sv:183.14-215.21" *) wdata_i : { s_cfg_lo_reg[31:2], 1'hx, s_cfg_lo_reg[0] };
  assign \$procmux$769_CMP  = ! (* src = "../rtl/timer_unit/timer_unit.sv:186.4-186.33|../rtl/timer_unit/timer_unit.sv:183.14-215.21" *) addr_i[5:0];
  assign \$auto$slang_frontend.cc:694:finish$\s_reset_timer_hi$36  = addr_i[5:0] == (* src = "../rtl/timer_unit/timer_unit.sv:213.4-213.30|../rtl/timer_unit/timer_unit.sv:183.14-215.21" *) 6'h24;
  assign \$auto$slang_frontend.cc:694:finish$\s_reset_timer_lo$35  = addr_i[5:0] == (* src = "../rtl/timer_unit/timer_unit.sv:210.4-210.30|../rtl/timer_unit/timer_unit.sv:183.14-215.21" *) 6'h20;
  assign \$auto$slang_frontend.cc:694:finish$\s_start_timer_hi$34  = addr_i[5:0] == (* src = "../rtl/timer_unit/timer_unit.sv:207.4-207.30|../rtl/timer_unit/timer_unit.sv:183.14-215.21" *) 5'h1c;
  assign \$auto$slang_frontend.cc:694:finish$\s_start_timer_lo$33  = addr_i[5:0] == (* src = "../rtl/timer_unit/timer_unit.sv:204.4-204.30|../rtl/timer_unit/timer_unit.sv:183.14-215.21" *) 5'h18;
  assign \$auto$slang_frontend.cc:694:finish$\s_write_counter_hi$32  = addr_i[5:0] == (* src = "../rtl/timer_unit/timer_unit.sv:195.4-195.30|../rtl/timer_unit/timer_unit.sv:183.14-215.21" *) 4'hc;
  assign \$auto$slang_frontend.cc:694:finish$\s_write_counter_lo$31  = addr_i[5:0] == (* src = "../rtl/timer_unit/timer_unit.sv:192.4-192.30|../rtl/timer_unit/timer_unit.sv:183.14-215.21" *) 4'h8;
  assign { s_cfg_hi[31:2], \$auto$slang_frontend.cc:694:finish$\s_cfg_hi$48 [1:0] } = \$auto$builder.cc:338:Biop$28  ? (* src = "../rtl/timer_unit/timer_unit.sv:183.14-215.21|../rtl/timer_unit/timer_unit.sv:180.9-216.14" *) \$auto$slang_frontend.cc:694:finish$\s_cfg_hi$38  : { s_cfg_hi_reg[31:2], 1'hx, s_cfg_hi_reg[0] };
  assign { s_cfg_lo[31:2], \$auto$slang_frontend.cc:694:finish$\s_cfg_lo$47 [1:0] } = \$auto$builder.cc:338:Biop$28  ? (* src = "../rtl/timer_unit/timer_unit.sv:183.14-215.21|../rtl/timer_unit/timer_unit.sv:180.9-216.14" *) \$auto$slang_frontend.cc:694:finish$\s_cfg_lo$37  : { s_cfg_lo_reg[31:2], 1'hx, s_cfg_lo_reg[0] };
  assign s_reset_timer_hi = \$auto$builder.cc:338:Biop$28  & (* src = "../rtl/timer_unit/timer_unit.sv:183.14-215.21|../rtl/timer_unit/timer_unit.sv:180.9-216.14" *) \$auto$slang_frontend.cc:694:finish$\s_reset_timer_hi$36 ;
  assign s_reset_timer_lo = \$auto$builder.cc:338:Biop$28  & (* src = "../rtl/timer_unit/timer_unit.sv:183.14-215.21|../rtl/timer_unit/timer_unit.sv:180.9-216.14" *) \$auto$slang_frontend.cc:694:finish$\s_reset_timer_lo$35 ;
  assign s_start_timer_hi = \$auto$builder.cc:338:Biop$28  & (* src = "../rtl/timer_unit/timer_unit.sv:183.14-215.21|../rtl/timer_unit/timer_unit.sv:180.9-216.14" *) \$auto$slang_frontend.cc:694:finish$\s_start_timer_hi$34 ;
  assign s_start_timer_lo = \$auto$builder.cc:338:Biop$28  & (* src = "../rtl/timer_unit/timer_unit.sv:183.14-215.21|../rtl/timer_unit/timer_unit.sv:180.9-216.14" *) \$auto$slang_frontend.cc:694:finish$\s_start_timer_lo$33 ;
  assign s_write_counter_hi = \$auto$builder.cc:338:Biop$28  & (* src = "../rtl/timer_unit/timer_unit.sv:183.14-215.21|../rtl/timer_unit/timer_unit.sv:180.9-216.14" *) \$auto$slang_frontend.cc:694:finish$\s_write_counter_hi$32 ;
  assign s_write_counter_lo = \$auto$builder.cc:338:Biop$28  & (* src = "../rtl/timer_unit/timer_unit.sv:183.14-215.21|../rtl/timer_unit/timer_unit.sv:180.9-216.14" *) \$auto$slang_frontend.cc:694:finish$\s_write_counter_lo$31 ;
  assign \$auto$slang_frontend.cc:694:finish$\s_enable_count_prescaler_lo$271  = \$auto$builder.cc:338:Biop$267  ? (* full_case = 32'd1 *) (* src = "../rtl/timer_unit/timer_unit.sv:453.3-457.6|../rtl/timer_unit/timer_unit.sv:452.14-463.6" *) s_ref_clk_edge : 1'h1;
  assign \$auto$slang_frontend.cc:694:finish$\s_enable_count_lo$272  = \$auto$builder.cc:338:Biop$259  ? (* full_case = 32'd1 *) (* src = "../rtl/timer_unit/timer_unit.sv:448.3-451.6|../rtl/timer_unit/timer_unit.sv:447.11-463.6" *) s_ref_clk_edge : s_target_reached_prescaler_lo;
  assign \$auto$slang_frontend.cc:694:finish$\s_enable_count_prescaler_lo$367  = \$auto$builder.cc:338:Biop$259  ? (* full_case = 32'd1 *) (* src = "../rtl/timer_unit/timer_unit.sv:448.3-451.6|../rtl/timer_unit/timer_unit.sv:447.11-463.6" *) \$auto$slang_frontend.cc:694:finish$\s_enable_count_prescaler_lo$277  : \$auto$slang_frontend.cc:694:finish$\s_enable_count_prescaler_lo$271 ;
  assign \$auto$slang_frontend.cc:694:finish$\s_enable_count_hi$369  = \$auto$builder.cc:338:Biop$251  ? (* full_case = 32'd1 *) (* src = "../rtl/timer_unit/timer_unit.sv:443.6-446.9|../rtl/timer_unit/timer_unit.sv:442.6-463.6" *) \$auto$builder.cc:338:Biop$331  : \$auto$opt_share.cc:222:merge_operators$1217 ;
  assign \$auto$slang_frontend.cc:694:finish$\s_enable_count_prescaler_lo$370  = \$auto$builder.cc:338:Biop$251  ? (* full_case = 32'd1 *) (* src = "../rtl/timer_unit/timer_unit.sv:443.6-446.9|../rtl/timer_unit/timer_unit.sv:442.6-463.6" *) \$auto$slang_frontend.cc:694:finish$\s_enable_count_prescaler_lo$277  : \$auto$slang_frontend.cc:694:finish$\s_enable_count_prescaler_lo$367 ;
  assign s_enable_count_prescaler_lo = \$auto$builder.cc:338:Biop$319  ? (* src = "../rtl/timer_unit/timer_unit.sv:442.6-463.6|../rtl/timer_unit/timer_unit.sv:440.2-464.7" *) \$auto$slang_frontend.cc:694:finish$\s_enable_count_prescaler_lo$370  : \$auto$slang_frontend.cc:694:finish$\s_enable_count_prescaler_lo$277 ;
  assign s_enable_count_hi = \$auto$builder.cc:338:Biop$319  ? (* src = "../rtl/timer_unit/timer_unit.sv:442.6-463.6|../rtl/timer_unit/timer_unit.sv:440.2-464.7" *) \$auto$slang_frontend.cc:694:finish$\s_enable_count_hi$369  : \$auto$slang_frontend.cc:694:finish$\s_enable_count_hi$312 ;
  assign s_enable_count_lo = \$auto$builder.cc:338:Biop$319  ? (* src = "../rtl/timer_unit/timer_unit.sv:442.6-463.6|../rtl/timer_unit/timer_unit.sv:440.2-464.7" *) \$auto$slang_frontend.cc:694:finish$\s_enable_count_lo$274  : \$auto$slang_frontend.cc:694:finish$\s_enable_count_lo$276 ;
  assign \$auto$slang_frontend.cc:694:finish$\s_enable_count_prescaler_hi$307  = \$auto$builder.cc:338:Biop$303  ? (* full_case = 32'd1 *) (* src = "../rtl/timer_unit/timer_unit.sv:428.6-431.9|../rtl/timer_unit/timer_unit.sv:427.4-436.9" *) s_ref_clk_edge : 1'h1;
  assign \$auto$slang_frontend.cc:694:finish$\s_enable_count_hi$308  = \$auto$builder.cc:338:Biop$295  ? (* full_case = 32'd1 *) (* src = "../rtl/timer_unit/timer_unit.sv:424.7-424.42|../rtl/timer_unit/timer_unit.sv:422.9-436.9" *) s_ref_clk_edge : s_target_reached_prescaler_hi;
  assign \$auto$slang_frontend.cc:694:finish$\s_enable_count_prescaler_hi$309  = \$auto$builder.cc:338:Biop$295  ? (* full_case = 32'd1 *) (* src = "../rtl/timer_unit/timer_unit.sv:424.7-424.42|../rtl/timer_unit/timer_unit.sv:422.9-436.9" *) 1'h0 : \$auto$slang_frontend.cc:694:finish$\s_enable_count_prescaler_hi$307 ;
  (* src = "../rtl/timer_unit/timer_unit.sv:561.23" *)
  \timer_unit_counter$timer_unit.counter_hi_i  counter_hi_i (
    .clk_i(clk_i),
    .compare_value_i(s_timer_cmp_hi_reg),
    .counter_value_i(wdata_i),
    .counter_value_o(s_timer_val_hi),
    .enable_count_i(s_enable_count_hi),
    .reset_count_i(s_reset_count_hi),
    .rst_ni(rst_ni),
    .target_reached_o(s_target_reached_hi),
    .write_counter_i(s_write_counter_hi)
  );
  (* src = "../rtl/timer_unit/timer_unit.sv:545.23" *)
  \timer_unit_counter$timer_unit.counter_lo_i  counter_lo_i (
    .clk_i(clk_i),
    .compare_value_i(s_timer_cmp_lo_reg),
    .counter_value_i(wdata_i),
    .counter_value_o(s_timer_val_lo),
    .enable_count_i(s_enable_count_lo),
    .reset_count_i(s_reset_count_lo),
    .rst_ni(rst_ni),
    .target_reached_o(s_target_reached_lo),
    .write_counter_i(s_write_counter_lo)
  );
  (* src = "../rtl/timer_unit/timer_unit.sv:529.29" *)
  \timer_unit_counter_presc$timer_unit.prescaler_hi_i  prescaler_hi_i (
    .clk_i(clk_i),
    .compare_value_i({ 24'h000000, s_cfg_hi_reg[15:8] }),
    .counter_value_i(32'd0),
    .enable_count_i(s_enable_count_prescaler_hi),
    .reset_count_i(s_reset_count_prescaler_hi),
    .rst_ni(rst_ni),
    .target_reached_o(s_target_reached_prescaler_hi),
    .write_counter_i(1'h0)
  );
  (* src = "../rtl/timer_unit/timer_unit.sv:513.29" *)
  \timer_unit_counter_presc$timer_unit.prescaler_lo_i  prescaler_lo_i (
    .clk_i(clk_i),
    .compare_value_i({ 24'h000000, s_cfg_lo_reg[15:8] }),
    .counter_value_i(32'd0),
    .enable_count_i(s_enable_count_prescaler_lo),
    .reset_count_i(s_reset_count_prescaler_lo),
    .rst_ni(rst_ni),
    .target_reached_o(s_target_reached_prescaler_lo),
    .write_counter_i(1'h0)
  );
  assign \$auto$slang_frontend.cc:694:finish$\s_cfg_hi$48 [31:2] = s_cfg_hi[31:2];
  assign \$auto$slang_frontend.cc:694:finish$\s_cfg_lo$47 [31:2] = s_cfg_lo[31:2];
  assign gnt_o = 1'h1;
  assign r_opc_o = 1'h0;
endmodule

(* src = "../rtl/timer_unit/timer_unit_counter.sv:13.8" *)
module \timer_unit_counter$timer_unit.counter_hi_i (clk_i, rst_ni, write_counter_i, counter_value_i, reset_count_i, enable_count_i, compare_value_i, target_reached_o, counter_value_o);
  wire [31:0] \$auto$builder.cc:338:Biop$537 ;
  wire \$auto$builder.cc:338:Biop$552 ;
  (* src = "../rtl/timer_unit/timer_unit_counter.sv:45.3-46.31" *)
  wire [31:0] \$auto$slang_frontend.cc:694:finish$\s_count$538 ;
  (* src = "../rtl/timer_unit/timer_unit_counter.sv:41.5-47.10" *)
  wire [31:0] \$auto$slang_frontend.cc:694:finish$\s_count$539 ;
  (* src = "../rtl/timer_unit/timer_unit_counter.sv:15.24" *)
  input clk_i;
  wire clk_i;
  (* src = "../rtl/timer_unit/timer_unit_counter.sv:23.24" *)
  input [31:0] compare_value_i;
  wire [31:0] compare_value_i;
  (* src = "../rtl/timer_unit/timer_unit_counter.sv:19.24" *)
  input [31:0] counter_value_i;
  wire [31:0] counter_value_i;
  (* src = "../rtl/timer_unit/timer_unit_counter.sv:25.24" *)
  output [31:0] counter_value_o;
  reg [31:0] counter_value_o;
  (* src = "../rtl/timer_unit/timer_unit_counter.sv:22.24" *)
  input enable_count_i;
  wire enable_count_i;
  (* src = "../rtl/timer_unit/timer_unit_counter.sv:21.24" *)
  input reset_count_i;
  wire reset_count_i;
  (* src = "../rtl/timer_unit/timer_unit_counter.sv:16.24" *)
  input rst_ni;
  wire rst_ni;
  (* src = "../rtl/timer_unit/timer_unit_counter.sv:29.24" *)
  wire [31:0] s_count;
  (* src = "../rtl/timer_unit/timer_unit_counter.sv:26.24" *)
  output target_reached_o;
  reg target_reached_o;
  (* src = "../rtl/timer_unit/timer_unit_counter.sv:18.24" *)
  input write_counter_i;
  wire write_counter_i;
  assign \$auto$builder.cc:338:Biop$537  = counter_value_o + 1'h1;
  assign \$auto$builder.cc:338:Biop$552  = s_count == compare_value_i;
  (* src = "../rtl/timer_unit/timer_unit_counter.sv:51.4" *)
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) counter_value_o <= 32'd0;
    else counter_value_o <= s_count;
  (* src = "../rtl/timer_unit/timer_unit_counter.sv:60.4" *)
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) target_reached_o <= 1'h0;
    else target_reached_o <= \$auto$builder.cc:338:Biop$552 ;
  assign \$auto$slang_frontend.cc:694:finish$\s_count$538  = enable_count_i ? (* src = "../rtl/timer_unit/timer_unit_counter.sv:46.5-46.31|../rtl/timer_unit/timer_unit_counter.sv:45.3-46.31" *) \$auto$builder.cc:338:Biop$537  : counter_value_o;
  assign \$auto$slang_frontend.cc:694:finish$\s_count$539  = write_counter_i ? (* full_case = 32'd1 *) (* src = "../rtl/timer_unit/timer_unit_counter.sv:42.7-42.33|../rtl/timer_unit/timer_unit_counter.sv:41.5-47.10" *) counter_value_i : \$auto$slang_frontend.cc:694:finish$\s_count$538 ;
  assign s_count = reset_count_i ? (* full_case = 32'd1 *) (* src = "../rtl/timer_unit/timer_unit_counter.sv:38.10-38.22|../rtl/timer_unit/timer_unit_counter.sv:37.7-48.5" *) 32'd0 : \$auto$slang_frontend.cc:694:finish$\s_count$539 ;
endmodule

(* src = "../rtl/timer_unit/timer_unit_counter.sv:13.8" *)
module \timer_unit_counter$timer_unit.counter_lo_i (clk_i, rst_ni, write_counter_i, counter_value_i, reset_count_i, enable_count_i, compare_value_i, target_reached_o, counter_value_o);
  wire [31:0] \$auto$builder.cc:338:Biop$504 ;
  wire \$auto$builder.cc:338:Biop$519 ;
  (* src = "../rtl/timer_unit/timer_unit_counter.sv:45.3-46.31" *)
  wire [31:0] \$auto$slang_frontend.cc:694:finish$\s_count$505 ;
  (* src = "../rtl/timer_unit/timer_unit_counter.sv:41.5-47.10" *)
  wire [31:0] \$auto$slang_frontend.cc:694:finish$\s_count$506 ;
  (* src = "../rtl/timer_unit/timer_unit_counter.sv:15.24" *)
  input clk_i;
  wire clk_i;
  (* src = "../rtl/timer_unit/timer_unit_counter.sv:23.24" *)
  input [31:0] compare_value_i;
  wire [31:0] compare_value_i;
  (* src = "../rtl/timer_unit/timer_unit_counter.sv:19.24" *)
  input [31:0] counter_value_i;
  wire [31:0] counter_value_i;
  (* src = "../rtl/timer_unit/timer_unit_counter.sv:25.24" *)
  output [31:0] counter_value_o;
  reg [31:0] counter_value_o;
  (* src = "../rtl/timer_unit/timer_unit_counter.sv:22.24" *)
  input enable_count_i;
  wire enable_count_i;
  (* src = "../rtl/timer_unit/timer_unit_counter.sv:21.24" *)
  input reset_count_i;
  wire reset_count_i;
  (* src = "../rtl/timer_unit/timer_unit_counter.sv:16.24" *)
  input rst_ni;
  wire rst_ni;
  (* src = "../rtl/timer_unit/timer_unit_counter.sv:29.24" *)
  wire [31:0] s_count;
  (* src = "../rtl/timer_unit/timer_unit_counter.sv:26.24" *)
  output target_reached_o;
  reg target_reached_o;
  (* src = "../rtl/timer_unit/timer_unit_counter.sv:18.24" *)
  input write_counter_i;
  wire write_counter_i;
  assign \$auto$builder.cc:338:Biop$504  = counter_value_o + 1'h1;
  assign \$auto$builder.cc:338:Biop$519  = s_count == compare_value_i;
  (* src = "../rtl/timer_unit/timer_unit_counter.sv:51.4" *)
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) counter_value_o <= 32'd0;
    else counter_value_o <= s_count;
  (* src = "../rtl/timer_unit/timer_unit_counter.sv:60.4" *)
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) target_reached_o <= 1'h0;
    else target_reached_o <= \$auto$builder.cc:338:Biop$519 ;
  assign \$auto$slang_frontend.cc:694:finish$\s_count$505  = enable_count_i ? (* src = "../rtl/timer_unit/timer_unit_counter.sv:46.5-46.31|../rtl/timer_unit/timer_unit_counter.sv:45.3-46.31" *) \$auto$builder.cc:338:Biop$504  : counter_value_o;
  assign \$auto$slang_frontend.cc:694:finish$\s_count$506  = write_counter_i ? (* full_case = 32'd1 *) (* src = "../rtl/timer_unit/timer_unit_counter.sv:42.7-42.33|../rtl/timer_unit/timer_unit_counter.sv:41.5-47.10" *) counter_value_i : \$auto$slang_frontend.cc:694:finish$\s_count$505 ;
  assign s_count = reset_count_i ? (* full_case = 32'd1 *) (* src = "../rtl/timer_unit/timer_unit_counter.sv:38.10-38.22|../rtl/timer_unit/timer_unit_counter.sv:37.7-48.5" *) 32'd0 : \$auto$slang_frontend.cc:694:finish$\s_count$506 ;
endmodule

(* src = "../rtl/timer_unit/timer_unit_counter_presc.sv:13.8" *)
module \timer_unit_counter_presc$timer_unit.prescaler_hi_i (clk_i, rst_ni, write_counter_i, counter_value_i, reset_count_i, enable_count_i, compare_value_i, target_reached_o, counter_value_o);
  wire \$auto$builder.cc:338:Biop$459 ;
  wire [31:0] \$auto$builder.cc:338:Biop$471 ;
  wire \$auto$builder.cc:338:Biop$486 ;
  (* src = "../rtl/timer_unit/timer_unit_counter_presc.sv:45.14-46.42" *)
  wire [31:0] \$auto$slang_frontend.cc:694:finish$\s_count$472 ;
  (* src = "../rtl/timer_unit/timer_unit_counter_presc.sv:41.9-47.12" *)
  wire [31:0] \$auto$slang_frontend.cc:694:finish$\s_count$473 ;
  (* src = "../rtl/timer_unit/timer_unit_counter_presc.sv:15.24" *)
  input clk_i;
  wire clk_i;
  (* src = "../rtl/timer_unit/timer_unit_counter_presc.sv:23.24" *)
  input [31:0] compare_value_i;
  wire [31:0] compare_value_i;
  (* src = "../rtl/timer_unit/timer_unit_counter_presc.sv:19.24" *)
  input [31:0] counter_value_i;
  wire [31:0] counter_value_i;
  (* src = "../rtl/timer_unit/timer_unit_counter_presc.sv:25.24" *)
  output [31:0] counter_value_o;
  reg [31:0] counter_value_o;
  (* src = "../rtl/timer_unit/timer_unit_counter_presc.sv:22.24" *)
  input enable_count_i;
  wire enable_count_i;
  (* src = "../rtl/timer_unit/timer_unit_counter_presc.sv:21.24" *)
  input reset_count_i;
  wire reset_count_i;
  (* src = "../rtl/timer_unit/timer_unit_counter_presc.sv:16.24" *)
  input rst_ni;
  wire rst_ni;
  (* src = "../rtl/timer_unit/timer_unit_counter_presc.sv:29.24" *)
  wire [31:0] s_count;
  (* src = "../rtl/timer_unit/timer_unit_counter_presc.sv:26.24" *)
  output target_reached_o;
  reg target_reached_o;
  (* src = "../rtl/timer_unit/timer_unit_counter_presc.sv:18.24" *)
  input write_counter_i;
  wire write_counter_i;
  assign \$auto$builder.cc:338:Biop$459  = reset_count_i || target_reached_o;
  assign \$auto$builder.cc:338:Biop$471  = counter_value_o + 1'h1;
  assign \$auto$builder.cc:338:Biop$486  = s_count == compare_value_i;
  (* src = "../rtl/timer_unit/timer_unit_counter_presc.sv:51.4" *)
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) counter_value_o <= 32'd0;
    else counter_value_o <= s_count;
  (* src = "../rtl/timer_unit/timer_unit_counter_presc.sv:60.4" *)
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) target_reached_o <= 1'h0;
    else target_reached_o <= \$auto$builder.cc:338:Biop$486 ;
  assign \$auto$slang_frontend.cc:694:finish$\s_count$472  = enable_count_i ? (* src = "../rtl/timer_unit/timer_unit_counter_presc.sv:46.16-46.42|../rtl/timer_unit/timer_unit_counter_presc.sv:45.14-46.42" *) \$auto$builder.cc:338:Biop$471  : counter_value_o;
  assign \$auto$slang_frontend.cc:694:finish$\s_count$473  = write_counter_i ? (* full_case = 32'd1 *) (* src = "../rtl/timer_unit/timer_unit_counter_presc.sv:42.12-42.38|../rtl/timer_unit/timer_unit_counter_presc.sv:41.9-47.12" *) counter_value_i : \$auto$slang_frontend.cc:694:finish$\s_count$472 ;
  assign s_count = \$auto$builder.cc:338:Biop$459  ? (* full_case = 32'd1 *) (* src = "../rtl/timer_unit/timer_unit_counter_presc.sv:38.8-38.20|../rtl/timer_unit/timer_unit_counter_presc.sv:37.6-48.9" *) 32'd0 : \$auto$slang_frontend.cc:694:finish$\s_count$473 ;
endmodule

(* src = "../rtl/timer_unit/timer_unit_counter_presc.sv:13.8" *)
module \timer_unit_counter_presc$timer_unit.prescaler_lo_i (clk_i, rst_ni, write_counter_i, counter_value_i, reset_count_i, enable_count_i, compare_value_i, target_reached_o, counter_value_o);
  wire \$auto$builder.cc:338:Biop$422 ;
  wire [31:0] \$auto$builder.cc:338:Biop$434 ;
  wire \$auto$builder.cc:338:Biop$449 ;
  (* src = "../rtl/timer_unit/timer_unit_counter_presc.sv:45.14-46.42" *)
  wire [31:0] \$auto$slang_frontend.cc:694:finish$\s_count$435 ;
  (* src = "../rtl/timer_unit/timer_unit_counter_presc.sv:41.9-47.12" *)
  wire [31:0] \$auto$slang_frontend.cc:694:finish$\s_count$436 ;
  (* src = "../rtl/timer_unit/timer_unit_counter_presc.sv:15.24" *)
  input clk_i;
  wire clk_i;
  (* src = "../rtl/timer_unit/timer_unit_counter_presc.sv:23.24" *)
  input [31:0] compare_value_i;
  wire [31:0] compare_value_i;
  (* src = "../rtl/timer_unit/timer_unit_counter_presc.sv:19.24" *)
  input [31:0] counter_value_i;
  wire [31:0] counter_value_i;
  (* src = "../rtl/timer_unit/timer_unit_counter_presc.sv:25.24" *)
  output [31:0] counter_value_o;
  reg [31:0] counter_value_o;
  (* src = "../rtl/timer_unit/timer_unit_counter_presc.sv:22.24" *)
  input enable_count_i;
  wire enable_count_i;
  (* src = "../rtl/timer_unit/timer_unit_counter_presc.sv:21.24" *)
  input reset_count_i;
  wire reset_count_i;
  (* src = "../rtl/timer_unit/timer_unit_counter_presc.sv:16.24" *)
  input rst_ni;
  wire rst_ni;
  (* src = "../rtl/timer_unit/timer_unit_counter_presc.sv:29.24" *)
  wire [31:0] s_count;
  (* src = "../rtl/timer_unit/timer_unit_counter_presc.sv:26.24" *)
  output target_reached_o;
  reg target_reached_o;
  (* src = "../rtl/timer_unit/timer_unit_counter_presc.sv:18.24" *)
  input write_counter_i;
  wire write_counter_i;
  assign \$auto$builder.cc:338:Biop$422  = reset_count_i || target_reached_o;
  assign \$auto$builder.cc:338:Biop$434  = counter_value_o + 1'h1;
  assign \$auto$builder.cc:338:Biop$449  = s_count == compare_value_i;
  (* src = "../rtl/timer_unit/timer_unit_counter_presc.sv:51.4" *)
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) counter_value_o <= 32'd0;
    else counter_value_o <= s_count;
  (* src = "../rtl/timer_unit/timer_unit_counter_presc.sv:60.4" *)
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) target_reached_o <= 1'h0;
    else target_reached_o <= \$auto$builder.cc:338:Biop$449 ;
  assign \$auto$slang_frontend.cc:694:finish$\s_count$435  = enable_count_i ? (* src = "../rtl/timer_unit/timer_unit_counter_presc.sv:46.16-46.42|../rtl/timer_unit/timer_unit_counter_presc.sv:45.14-46.42" *) \$auto$builder.cc:338:Biop$434  : counter_value_o;
  assign \$auto$slang_frontend.cc:694:finish$\s_count$436  = write_counter_i ? (* full_case = 32'd1 *) (* src = "../rtl/timer_unit/timer_unit_counter_presc.sv:42.12-42.38|../rtl/timer_unit/timer_unit_counter_presc.sv:41.9-47.12" *) counter_value_i : \$auto$slang_frontend.cc:694:finish$\s_count$435 ;
  assign s_count = \$auto$builder.cc:338:Biop$422  ? (* full_case = 32'd1 *) (* src = "../rtl/timer_unit/timer_unit_counter_presc.sv:38.8-38.20|../rtl/timer_unit/timer_unit_counter_presc.sv:37.6-48.9" *) 32'd0 : \$auto$slang_frontend.cc:694:finish$\s_count$436 ;
endmodule
